"""add_item_zone_to_items

Revision ID: 03cfb5308256
Revises: a4f9c2d7e6b1
Create Date: 2026-07-06 17:07:53.540494
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '03cfb5308256'
down_revision: Union[str, None] = 'a4f9c2d7e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("item_zone", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "item_zone")
    # ### end Alembic commands ###
