"""create_stock_report_tables

Revision ID: 10d97764a5a7
Revises: ce99896e6f49
Create Date: 2026-09-19 17:16:13.014825
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "10d97764a5a7"
down_revision: Union[str, None] = "ce99896e6f49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_report_repair_records",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "target_kind",
            sa.Enum(
                "stock_report_item",
                "history_record",
                "task",
                "group",
                name="stock_report_repair_target_kind_enum",
            ),
            nullable=False,
        ),
        sa.Column("target_client_id", sa.String(length=64), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("stored_value", sa.Text(), nullable=True),
        sa.Column("recomputed_value", sa.Text(), nullable=True),
        sa.Column("trigger", sa.String(length=64), nullable=False),
        sa.Column("created_by_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_stock_report_repair_records_created_by_id"),
        "stock_report_repair_records",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_repair_records_target_client_id"),
        "stock_report_repair_records",
        ["target_client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_repair_records_target_kind"),
        "stock_report_repair_records",
        ["target_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_repair_records_workspace_id"),
        "stock_report_repair_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "stock_report_items",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("item_category_id", sa.String(length=64), nullable=False),
        sa.Column(
            "properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("properties_signature", sa.String(length=64), nullable=False),
        sa.Column(
            "quantity_requested", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_in_queue", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_in_progress", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_awaiting", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "priority",
            sa.Enum("high", "medium", "low", name="stock_report_priority_enum"),
            nullable=True,
        ),
        sa.Column("priority_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_id", sa.String(length=64), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "quantity_awaiting >= 0",
            name="ck_stock_report_items_quantity_awaiting_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_in_progress >= 0",
            name="ck_stock_report_items_quantity_in_progress_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_in_queue >= 0",
            name="ck_stock_report_items_quantity_in_queue_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_requested >= 0",
            name="ck_stock_report_items_quantity_requested_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["item_category_id"], ["item_categories.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_stock_report_items_created_by_id"),
        "stock_report_items",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_items_item_category_id"),
        "stock_report_items",
        ["item_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_items_workspace_id"),
        "stock_report_items",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_report_items_workspace_priority_order",
        "stock_report_items",
        ["workspace_id", "priority", "priority_order"],
        unique=False,
    )
    op.create_index(
        "uix_stock_report_items_identity_active",
        "stock_report_items",
        ["workspace_id", "item_category_id", "properties_signature"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "stock_report_history_records",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("stock_report_item_id", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "quantity_requested_change",
                "priority_change",
                "priority_order_change",
                name="stock_report_history_record_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_requested", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_awaiting", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "priority",
            sa.Enum("high", "medium", "low", name="stock_report_priority_enum"),
            nullable=True,
        ),
        sa.Column("priority_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.String(length=64), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "quantity_awaiting >= 0",
            name="ck_stock_report_history_records_quantity_awaiting_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["stock_report_item_id"],
            ["stock_report_items.client_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_stock_report_history_records_created_by_id"),
        "stock_report_history_records",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_report_history_records_row_type_created",
        "stock_report_history_records",
        ["stock_report_item_id", "type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_history_records_stock_report_item_id"),
        "stock_report_history_records",
        ["stock_report_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_history_records_type"),
        "stock_report_history_records",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_history_records_workspace_id"),
        "stock_report_history_records",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "stock_task_assignments",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("stock_report_item_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("credited_history_record_id", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "property_mismatch_overridden",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "in_queue",
                "in_progress",
                "awaiting",
                "resolved",
                "failed",
                "resolved_early",
                name="stock_task_assignment_state_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_id", sa.String(length=64), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "quantity >= 1", name="ck_stock_task_assignments_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["credited_history_record_id"],
            ["stock_report_history_records.client_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.client_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["stock_report_item_id"],
            ["stock_report_items.client_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.client_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_stock_task_assignments_created_by_id"),
        "stock_task_assignments",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_credited_history_record_id"),
        "stock_task_assignments",
        ["credited_history_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_item_id"),
        "stock_task_assignments",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_task_assignments_row_state",
        "stock_task_assignments",
        ["stock_report_item_id", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_state"),
        "stock_task_assignments",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_stock_report_item_id"),
        "stock_task_assignments",
        ["stock_report_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_task_id"),
        "stock_task_assignments",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_task_assignments_workspace_id"),
        "stock_task_assignments",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "uix_stock_task_assignments_item_active",
        "stock_task_assignments",
        ["workspace_id", "item_id"],
        unique=True,
        postgresql_where=sa.text(
            "is_deleted = false AND state IN ('in_queue', 'in_progress', 'awaiting')"
        ),
    )
    op.create_index(
        "uix_stock_task_assignments_task_active",
        "stock_task_assignments",
        ["workspace_id", "task_id"],
        unique=True,
        postgresql_where=sa.text(
            "is_deleted = false AND state IN ('in_queue', 'in_progress', 'awaiting')"
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "is_stock_assignment",
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_stock_assignment")
    op.drop_index(
        "uix_stock_task_assignments_task_active",
        table_name="stock_task_assignments",
        postgresql_where=sa.text(
            "is_deleted = false AND state IN ('in_queue', 'in_progress', 'awaiting')"
        ),
    )
    op.drop_index(
        "uix_stock_task_assignments_item_active",
        table_name="stock_task_assignments",
        postgresql_where=sa.text(
            "is_deleted = false AND state IN ('in_queue', 'in_progress', 'awaiting')"
        ),
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_workspace_id"),
        table_name="stock_task_assignments",
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_task_id"), table_name="stock_task_assignments"
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_stock_report_item_id"),
        table_name="stock_task_assignments",
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_state"), table_name="stock_task_assignments"
    )
    op.drop_index(
        "ix_stock_task_assignments_row_state", table_name="stock_task_assignments"
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_item_id"), table_name="stock_task_assignments"
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_credited_history_record_id"),
        table_name="stock_task_assignments",
    )
    op.drop_index(
        op.f("ix_stock_task_assignments_created_by_id"),
        table_name="stock_task_assignments",
    )
    op.drop_table("stock_task_assignments")
    op.drop_index(
        op.f("ix_stock_report_history_records_workspace_id"),
        table_name="stock_report_history_records",
    )
    op.drop_index(
        op.f("ix_stock_report_history_records_type"),
        table_name="stock_report_history_records",
    )
    op.drop_index(
        op.f("ix_stock_report_history_records_stock_report_item_id"),
        table_name="stock_report_history_records",
    )
    op.drop_index(
        "ix_stock_report_history_records_row_type_created",
        table_name="stock_report_history_records",
    )
    op.drop_index(
        op.f("ix_stock_report_history_records_created_by_id"),
        table_name="stock_report_history_records",
    )
    op.drop_table("stock_report_history_records")
    op.drop_index(
        "uix_stock_report_items_identity_active",
        table_name="stock_report_items",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "ix_stock_report_items_workspace_priority_order",
        table_name="stock_report_items",
    )
    op.drop_index(
        op.f("ix_stock_report_items_workspace_id"), table_name="stock_report_items"
    )
    op.drop_index(
        op.f("ix_stock_report_items_item_category_id"), table_name="stock_report_items"
    )
    op.drop_index(
        op.f("ix_stock_report_items_created_by_id"), table_name="stock_report_items"
    )
    op.drop_table("stock_report_items")
    op.drop_index(
        op.f("ix_stock_report_repair_records_workspace_id"),
        table_name="stock_report_repair_records",
    )
    op.drop_index(
        op.f("ix_stock_report_repair_records_target_kind"),
        table_name="stock_report_repair_records",
    )
    op.drop_index(
        op.f("ix_stock_report_repair_records_target_client_id"),
        table_name="stock_report_repair_records",
    )
    op.drop_index(
        op.f("ix_stock_report_repair_records_created_by_id"),
        table_name="stock_report_repair_records",
    )
    op.drop_table("stock_report_repair_records")
    op.execute("DROP TYPE stock_task_assignment_state_enum")
    op.execute("DROP TYPE stock_report_priority_enum")
    op.execute("DROP TYPE stock_report_history_record_type_enum")
    op.execute("DROP TYPE stock_report_repair_target_kind_enum")
    # ### end Alembic commands ###
