"""create_stock_report_snapshot_tables

The snapshot layer over the live stock report: one `stock_report_snapshot_versions`
row per board version (at most one active per workspace, enforced by a partial unique
index) and one `stock_report_item_snapshots` row per live stock-report row inside it.

Hand-adjusted after autogenerate, two things the generator gets wrong here:

* `priority` reuses the Postgres type `stock_report_priority_enum` that
  `stock_report_items` created. Autogenerate emitted `sa.Enum(...)`, whose
  `create_table` fires `CREATE TYPE` and fails with `DuplicateObject`; it is declared
  `postgresql.ENUM(..., create_type=False)` instead, and the downgrade does **not**
  drop the type (`stock_report_history_records` still uses it).
* `ALTER TYPE ... ADD VALUE` is never autogenerated. It is written by hand and is
  safe inside this migration's transaction because nothing here uses the new value.

Autogenerate also listed three unrelated drifts (`email_sync_states_connection_id_key`
and two `step_state_records` indexes); they belong to other work and are not here.
The column drop on `stock_report_items` is the next revision (30_migrations: never
drop a column in the revision that creates its replacement).

Amended before publication (same day, unpushed): `quantity_resolved` — the
snapshot's completion memory, credited when Scanner resolves an assignment while the
snapshot is active — was added here rather than as a fourth revision, since no
environment beyond the dev database had run this chain.

Revision ID: 11e1d0d47686
Revises: 10d97764a5a7
Create Date: 2026-09-26 11:19:52.927350
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "11e1d0d47686"
down_revision: Union[str, None] = "10d97764a5a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PRIORITY_ENUM = postgresql.ENUM(
    "high", "medium", "low", name="stock_report_priority_enum", create_type=False
)


def upgrade() -> None:
    op.execute(
        "ALTER TYPE stock_report_repair_target_kind_enum "
        "ADD VALUE IF NOT EXISTS 'item_snapshot'"
    )

    op.create_table(
        "stock_report_snapshot_versions",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.String(length=64), nullable=True),
        sa.Column("closed_by_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_stock_report_snapshot_versions_created_by_id"),
        "stock_report_snapshot_versions",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_report_snapshot_versions_workspace_active_at",
        "stock_report_snapshot_versions",
        ["workspace_id", "active_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_snapshot_versions_workspace_id"),
        "stock_report_snapshot_versions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "uix_stock_report_snapshot_versions_active",
        "stock_report_snapshot_versions",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )

    op.create_table(
        "stock_report_item_snapshots",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("stock_report_item_id", sa.String(length=64), nullable=False),
        sa.Column(
            "quantity_requested", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_in_queue", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_in_progress", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "quantity_awaiting", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("quantity_missing", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quantity_resolved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority", _PRIORITY_ENUM, nullable=True),
        sa.Column("priority_order", sa.Integer(), nullable=True),
        sa.Column("active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(priority IS NULL) = (priority_order IS NULL)",
            name="ck_stock_report_item_snapshots_priority_order_pairing",
        ),
        sa.CheckConstraint(
            "quantity_awaiting >= 0",
            name="ck_stock_report_item_snapshots_quantity_awaiting_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_in_progress >= 0",
            name="ck_stock_report_item_snapshots_quantity_in_progress_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_in_queue >= 0",
            name="ck_stock_report_item_snapshots_quantity_in_queue_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_missing >= 0",
            name="ck_stock_report_item_snapshots_quantity_missing_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_requested >= 0",
            name="ck_stock_report_item_snapshots_quantity_requested_nonneg",
        ),
        sa.CheckConstraint(
            "quantity_resolved >= 0",
            name="ck_stock_report_item_snapshots_quantity_resolved_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["stock_report_item_id"],
            ["stock_report_items.client_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.client_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["stock_report_snapshot_versions.client_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.client_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint(
            "version_id",
            "stock_report_item_id",
            name="uq_stock_report_item_snapshots_version_row",
        ),
    )
    op.create_index(
        op.f("ix_stock_report_item_snapshots_stock_report_item_id"),
        "stock_report_item_snapshots",
        ["stock_report_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_item_snapshots_version_id"),
        "stock_report_item_snapshots",
        ["version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_report_item_snapshots_workspace_id"),
        "stock_report_item_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_report_item_snapshots_workspace_priority_order",
        "stock_report_item_snapshots",
        ["workspace_id", "priority", "priority_order"],
        unique=False,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_index(
        "uix_stock_report_item_snapshots_row_active",
        "stock_report_item_snapshots",
        ["workspace_id", "stock_report_item_id"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "uix_stock_report_item_snapshots_row_active",
        table_name="stock_report_item_snapshots",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index(
        "ix_stock_report_item_snapshots_workspace_priority_order",
        table_name="stock_report_item_snapshots",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_stock_report_item_snapshots_workspace_id"),
        table_name="stock_report_item_snapshots",
    )
    op.drop_index(
        op.f("ix_stock_report_item_snapshots_version_id"),
        table_name="stock_report_item_snapshots",
    )
    op.drop_index(
        op.f("ix_stock_report_item_snapshots_stock_report_item_id"),
        table_name="stock_report_item_snapshots",
    )
    op.drop_table("stock_report_item_snapshots")
    op.drop_index(
        "uix_stock_report_snapshot_versions_active",
        table_name="stock_report_snapshot_versions",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_stock_report_snapshot_versions_workspace_id"),
        table_name="stock_report_snapshot_versions",
    )
    op.drop_index(
        "ix_stock_report_snapshot_versions_workspace_active_at",
        table_name="stock_report_snapshot_versions",
    )
    op.drop_index(
        op.f("ix_stock_report_snapshot_versions_created_by_id"),
        table_name="stock_report_snapshot_versions",
    )
    op.drop_table("stock_report_snapshot_versions")
    # `stock_report_priority_enum` is owned by 10d97764a5a7 and still in use;
    # `item_snapshot` cannot be removed from the repair-target enum without recreating
    # the type, so both are left in place (30_migrations "Enum type migrations").
