"""add_upholstery_category

Revision ID: 183fb6115bd3
Revises: b5e8a7c2d4f1
Create Date: 2026-06-22 10:28:16.475730
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '183fb6115bd3'
down_revision: Union[str, None] = 'b5e8a7c2d4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upholstery_categories',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_upholstery_categories_workspace_name')
    )
    op.create_index(op.f('ix_upholstery_categories_created_by_id'), 'upholstery_categories', ['created_by_id'], unique=False)
    op.create_index('ix_upholstery_categories_workspace_favorite', 'upholstery_categories', ['workspace_id', 'favorite'], unique=False)
    op.create_index(op.f('ix_upholstery_categories_workspace_id'), 'upholstery_categories', ['workspace_id'], unique=False)
    op.add_column('upholsteries', sa.Column('upholstery_category_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_upholsteries_upholstery_category_id'), 'upholsteries', ['upholstery_category_id'], unique=False)
    op.create_foreign_key(None, 'upholsteries', 'upholstery_categories', ['upholstery_category_id'], ['client_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upholsteries', type_='foreignkey')
    op.drop_index(op.f('ix_upholsteries_upholstery_category_id'), table_name='upholsteries')
    op.drop_column('upholsteries', 'upholstery_category_id')
    op.drop_index(op.f('ix_upholstery_categories_workspace_id'), table_name='upholstery_categories')
    op.drop_index('ix_upholstery_categories_workspace_favorite', table_name='upholstery_categories')
    op.drop_index(op.f('ix_upholstery_categories_created_by_id'), table_name='upholstery_categories')
    op.drop_table('upholstery_categories')
    # ### end Alembic commands ###
