"""add_missing_circular_fks

Revision ID: 243e62bcd858
Revises: ddc5bf50153b
Create Date: 2026-05-15 12:35:12.496548
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '243e62bcd858'
down_revision: Union[str, None] = 'ddc5bf50153b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_customers_latest_history_record_id', 'customers', 'customer_history_records', ['latest_history_record_id'], ['client_id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_item_upholsteries_active_requirement_id', 'item_upholsteries', 'item_upholstery_requirements', ['active_requirement_id'], ['client_id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_task_steps_latest_state_record_id', 'task_steps', 'step_state_records', ['latest_state_record_id'], ['client_id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_tasks_latest_event_id', 'tasks', 'task_events', ['latest_event_id'], ['client_id'], ondelete='RESTRICT', use_alter=True)
    op.create_foreign_key('fk_tasks_latest_history_record_id', 'tasks', 'task_history_records', ['latest_history_record_id'], ['client_id'], ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_latest_history_record_id', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_latest_event_id', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_task_steps_latest_state_record_id', 'task_steps', type_='foreignkey')
    op.drop_constraint('fk_item_upholsteries_active_requirement_id', 'item_upholsteries', type_='foreignkey')
    op.drop_constraint('fk_customers_latest_history_record_id', 'customers', type_='foreignkey')
    # ### end Alembic commands ###
