"""collapse_ended_shift_step_state

Removes `ended_shift` from `task_step_state_enum` and reclassifies every historical row that
carried it. After this, a step that stopped because the shift ended is `paused`, and *why* it
stopped lives in `transition_reason` (the system) or `pause_reason_id` (the worker's choice).

The enum is **native** and shared by two tables (`step_state_records.state`,
`task_steps.state`), so removing a member means recreating the type and rewriting both
columns. Neither column has a default, and no other column uses the type — both verified
against the database before this was written.

## The reclassification, and the line that must not be crossed

| Historical row | Becomes |
|---|---|
| `transition_reason = 'shift_ended'` — the system force-closed it | `paused`, reason unchanged |
| `pause_reason_id` set — the worker picked it from the sheet | `paused`, reference kept, **no** `transition_reason` |
| neither set — a pre-typing clock-out | `paused`, `transition_reason = 'shift_ended'` |

The third row's default is why these are three statements and not one. A row carrying a
`pause_reason_id` is a **worker's stated choice**; typing it as a system transition would
silently relabel it as something the machine did, and the two are not distinguishable
afterwards. Each statement carries the predicate that excludes the other populations, and
the row counts are asserted to partition the population exactly.

Rows in `ended_shift` typed as some *other* system transition are not covered by any of the
three, and the migration **refuses** rather than guessing. (`ck_step_state_records_transition
_xor_catalog` already makes "both set" impossible, so that case cannot arise.)

## Reversibility — this migration IS reversible, while the journal lives

The plan called this irreversible. With the journal it is not, and that is worth having:
after the cutover a newly-written clock-out row (`state='paused'`,
`transition_reason='shift_ended'`) is byte-identical to a row this migration rewrote, and a
worker's pause is identical to a rewritten row-two — so **no predicate can identify the
rewritten rows afterwards**. That is exactly the condition `architecture/30_migrations.md`
says demands a journal.

`ended_shift_collapse_journal` therefore records every row it touched, with the state and
transition reason it had. `downgrade()` re-adds the enum member and restores precisely those
rows. What is *not* undone by any of this is the reporting change: a worker-picked
ended-shift pause moves from `total_ended_shift_seconds` to `total_pause_seconds` and past
reports read differently. That was decided deliberately (E2) and the journal does not soften
it — it only means the rows themselves can be put back.

The journal is a migration-owned table with no ORM model, named with the reserved `_journal`
suffix so `migrations/env.py`'s `include_object` filter does not let a later autogenerate
propose dropping it. Whichever change makes this one permanently irreversible must drop it
deliberately, last, behind an explicit environment acknowledgement, and record the row count
it held.

Hand-written rather than autogenerated, for the same reason as `97b60e06d42a`: this is a data
migration plus native-enum surgery, neither of which autogenerate can express, and
autogenerate would also sweep in pre-existing schema drift owned by the declared-worker-states
baseline.

Revision ID: 2645b4327b17
Revises: c8f3d2e60a17
Create Date: 2026-08-01 11:16:57.164166
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '2645b4327b17'
down_revision: Union[str, None] = 'c8f3d2e60a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ENUM = 'task_step_state_enum'
_OLD_ENUM = 'task_step_state_enum__pre_ended_shift_collapse'
_JOURNAL = 'ended_shift_collapse_journal'
_REMOVED = 'ended_shift'
_SHIFT_ENDED = 'shift_ended'

# The type as it must exist after this migration. Listed literally rather than derived from
# the Python enum: a migration is a historical record and must not change meaning when the
# application's enum does.
_MEMBERS_AFTER = (
    'pending', 'working', 'paused', 'blocked',
    'completed', 'skipped', 'failed', 'cancelled',
)
_MEMBERS_BEFORE = (
    'pending', 'working', 'paused', 'ended_shift', 'blocked',
    'completed', 'skipped', 'failed', 'cancelled',
)


def _enum_literal(members: Sequence[str]) -> str:
    return ', '.join(f"'{member}'" for member in members)


def _recreate_enum(members: Sequence[str]) -> None:
    """Swap `task_step_state_enum` for one with exactly ``members``, rewriting both columns.

    Postgres cannot remove a value from an enum in place. Renaming the old type out of the
    way, creating the new one, re-typing each column through `text`, then dropping the old
    type is the only route; the two `ALTER COLUMN ... TYPE` statements rewrite their tables
    and rebuild the indexes on `state`.
    """
    op.execute(f'ALTER TYPE {_ENUM} RENAME TO {_OLD_ENUM}')
    op.execute(f'CREATE TYPE {_ENUM} AS ENUM ({_enum_literal(members)})')
    for table in ('step_state_records', 'task_steps'):
        op.execute(
            f'ALTER TABLE {table} ALTER COLUMN state TYPE {_ENUM} '
            f'USING state::text::{_ENUM}'
        )
    op.execute(f'DROP TYPE {_OLD_ENUM}')


def _member_exists(bind, member: str) -> bool:
    return bool(
        bind.execute(
            sa.text(
                "SELECT count(*) FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid "
                "WHERE t.typname = :type_name AND e.enumlabel = :member"
            ),
            {"type_name": _ENUM, "member": member},
        ).scalar_one()
    )


def upgrade() -> None:
    bind = op.get_bind()

    if not _member_exists(bind, _REMOVED):
        print(f"[{revision}] '{_REMOVED}' is already absent from {_ENUM}; nothing to do")
        return

    # A row in `ended_shift` typed as a different system transition is not one of E2's three
    # cases. Refuse rather than guess which half of it is the true record.
    unclassifiable = bind.execute(
        sa.text(
            """
            SELECT count(*) FROM step_state_records
            WHERE state = :removed
              AND transition_reason IS NOT NULL
              AND transition_reason <> :shift_ended
            """
        ),
        {"removed": _REMOVED, "shift_ended": _SHIFT_ENDED},
    ).scalar_one()
    if unclassifiable:
        raise RuntimeError(
            f"ended-shift collapse refused: {unclassifiable} `step_state_records` rows are "
            f"in state '{_REMOVED}' while typed as a transition other than "
            f"'{_SHIFT_ENDED}'. No rule covers them — investigate before migrating; "
            "rewriting them would destroy real history."
        )

    op.execute(
        sa.text(
            f"""
            CREATE TABLE IF NOT EXISTS {_JOURNAL} (
                table_name                varchar(64) NOT NULL,
                client_id                 varchar(64) NOT NULL,
                previous_state            varchar(32) NOT NULL,
                previous_transition_reason varchar(32),
                e2_row                    smallint NOT NULL,
                PRIMARY KEY (table_name, client_id)
            )
            """
        )
    )

    # Journal first, and record which of E2's three rules claimed each row, so the audit
    # survives even if the counts below are read long after the fact.
    for e2_row, predicate in (
        (1, "transition_reason = :shift_ended"),
        (2, "transition_reason IS NULL AND pause_reason_id IS NOT NULL"),
        (3, "transition_reason IS NULL AND pause_reason_id IS NULL"),
    ):
        bind.execute(
            sa.text(
                f"""
                INSERT INTO {_JOURNAL}
                    (table_name, client_id, previous_state, previous_transition_reason, e2_row)
                SELECT 'step_state_records', client_id, state::text, transition_reason, {e2_row}
                FROM step_state_records
                WHERE state = :removed AND {predicate}
                ON CONFLICT (table_name, client_id) DO NOTHING
                """
            ),
            {"removed": _REMOVED, "shift_ended": _SHIFT_ENDED},
        )
    bind.execute(
        sa.text(
            f"""
            INSERT INTO {_JOURNAL}
                (table_name, client_id, previous_state, previous_transition_reason, e2_row)
            SELECT 'task_steps', client_id, state::text, NULL, 0
            FROM task_steps
            WHERE state = :removed
            ON CONFLICT (table_name, client_id) DO NOTHING
            """
        ),
        {"removed": _REMOVED},
    )

    # E2 row 1 — the system force-closed a working step. Already typed; only the state moves.
    row_one = bind.execute(
        sa.text(
            """
            UPDATE step_state_records SET state = 'paused'
            WHERE state = :removed AND transition_reason = :shift_ended
            """
        ),
        {"removed": _REMOVED, "shift_ended": _SHIFT_ENDED},
    ).rowcount

    # E2 row 2 — the worker picked this reason. The catalog reference is the explanation and
    # it is kept; `transition_reason` stays NULL. **Nothing below may touch these rows.**
    row_two = bind.execute(
        sa.text(
            """
            UPDATE step_state_records SET state = 'paused'
            WHERE state = :removed
              AND transition_reason IS NULL
              AND pause_reason_id IS NOT NULL
            """
        ),
        {"removed": _REMOVED},
    ).rowcount

    # E2 row 3 — a pre-typing clock-out: nobody said why, and the state was the only record
    # that the system stopped it. Typing it preserves its analytics bucket. The
    # `pause_reason_id IS NULL` predicate is what keeps row two out of this statement.
    row_three = bind.execute(
        sa.text(
            """
            UPDATE step_state_records
               SET state = 'paused', transition_reason = :shift_ended
            WHERE state = :removed
              AND transition_reason IS NULL
              AND pause_reason_id IS NULL
            """
        ),
        {"removed": _REMOVED, "shift_ended": _SHIFT_ENDED},
    ).rowcount

    # The step table carries no reason column. A step whose current state is a system-ended
    # pause is indistinguishable from an ordinary paused step, which is already how a
    # normally-paused step behaves.
    steps = bind.execute(
        sa.text("UPDATE task_steps SET state = 'paused' WHERE state = :removed"),
        {"removed": _REMOVED},
    ).rowcount

    print(
        f"[{revision}] reclassified step_state_records: "
        f"E2 row 1 (system-typed)={row_one}, row 2 (worker-picked)={row_two}, "
        f"row 3 (untyped)={row_three}; task_steps={steps}"
    )

    for table in ('step_state_records', 'task_steps'):
        remaining = bind.execute(
            sa.text(f"SELECT count(*) FROM {table} WHERE state = :removed"),
            {"removed": _REMOVED},
        ).scalar_one()
        if remaining:
            raise RuntimeError(
                f"ended-shift collapse incomplete: {remaining} `{table}` rows are still in "
                f"state '{_REMOVED}'; the enum member cannot be removed"
            )

    # A worker's stated choice must never come out of this typed as a system transition.
    # Asserted against the journal rather than the live rows, because after the rewrite the
    # two populations are no longer distinguishable — which is the whole reason it exists.
    mistyped = bind.execute(
        sa.text(
            f"""
            SELECT count(*) FROM {_JOURNAL} j
            JOIN step_state_records ssr ON ssr.client_id = j.client_id
            WHERE j.table_name = 'step_state_records'
              AND j.e2_row = 2
              AND ssr.transition_reason IS NOT NULL
            """
        )
    ).scalar_one()
    if mistyped:
        raise RuntimeError(
            f"ended-shift collapse corrupted {mistyped} rows: a record carrying a "
            "`pause_reason_id` was typed as a system transition, re-labelling a worker's "
            "stated choice as something the system did"
        )

    _recreate_enum(_MEMBERS_AFTER)


def downgrade() -> None:
    bind = op.get_bind()

    if _member_exists(bind, _REMOVED):
        print(f"[{revision}] '{_REMOVED}' is already present in {_ENUM}; nothing to do")
        return

    journal_exists = bind.execute(
        sa.text("SELECT to_regclass(:name) IS NOT NULL"), {"name": _JOURNAL}
    ).scalar_one()
    if not journal_exists:
        raise RuntimeError(
            f"Refusing to downgrade: `{_JOURNAL}` is gone, so the rows this migration "
            "rewrote can no longer be identified. Post-cutover writes are shape-identical "
            "to the rewritten rows, so restoring by predicate would corrupt live data. "
            "Recreating the enum member without restoring the rows is safe and can be done "
            "by hand if that is genuinely what is wanted."
        )

    # The member has to exist again before any row can be set back to it.
    _recreate_enum(_MEMBERS_BEFORE)

    restored_records = bind.execute(
        sa.text(
            f"""
            UPDATE step_state_records AS ssr
               SET state = j.previous_state::{_ENUM},
                   transition_reason = j.previous_transition_reason
            FROM {_JOURNAL} AS j
            WHERE j.table_name = 'step_state_records'
              AND j.client_id = ssr.client_id
            """
        )
    ).rowcount
    restored_steps = bind.execute(
        sa.text(
            f"""
            UPDATE task_steps AS ts
               SET state = j.previous_state::{_ENUM}
            FROM {_JOURNAL} AS j
            WHERE j.table_name = 'task_steps'
              AND j.client_id = ts.client_id
            """
        )
    ).rowcount
    print(
        f"[{revision}] restored step_state_records={restored_records}, "
        f"task_steps={restored_steps}"
    )

    op.execute(f'DROP TABLE IF EXISTS {_JOURNAL}')
