"""implement upholstery order and supplier tables

Revision ID: 38491ecd2b90
Revises: 7ab1c6d2e4f8
Create Date: 2026-06-16 15:04:43.421691
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '38491ecd2b90'
down_revision: Union[str, None] = '7ab1c6d2e4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_upholstery_currency_enum = postgresql.ENUM(
    "swedish_krona",
    "danish_krona",
    "euro",
    name="upholstery_currency_enum",
    create_type=False,
)

_upholstery_order_state_enum = postgresql.ENUM(
    "draft",
    "pending",
    "approved",
    "ordered",
    "failed",
    "cancelled",
    "partially_received",
    "received",
    name="upholstery_order_state_enum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _upholstery_order_state_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('suppliers',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_suppliers_workspace_name')
    )
    op.create_index(op.f('ix_suppliers_created_by_id'), 'suppliers', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_suppliers_workspace_id'), 'suppliers', ['workspace_id'], unique=False)
    op.create_table('upholstery_supplier_links',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.String(length=64), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=True),
    sa.Column('currency', _upholstery_currency_enum, nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('price_minor IS NULL OR price_minor >= 0', name='ck_upholstery_supplier_links_price_positive'),
    sa.CheckConstraint('priority_order IS NULL OR priority_order >= 0', name='ck_upholstery_supplier_links_priority_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_id'], ['upholsteries.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'upholstery_id', 'supplier_id', name='uq_upholstery_supplier_links_workspace_upholstery_supplier')
    )
    op.create_index(op.f('ix_upholstery_supplier_links_created_by_id'), 'upholstery_supplier_links', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholstery_supplier_links_supplier_id'), 'upholstery_supplier_links', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_upholstery_supplier_links_upholstery_id'), 'upholstery_supplier_links', ['upholstery_id'], unique=False)
    op.create_index(op.f('ix_upholstery_supplier_links_workspace_id'), 'upholstery_supplier_links', ['workspace_id'], unique=False)
    op.create_index('ix_upholstery_supplier_links_workspace_upholstery_preferred', 'upholstery_supplier_links', ['workspace_id', 'upholstery_id', 'preferred'], unique=False)
    op.create_table('upholstery_orders',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_inventory_id', sa.String(length=64), nullable=True),
    sa.Column('upholstery_supplier_link_id', sa.String(length=64), nullable=True),
    sa.Column('supplier_id', sa.String(length=64), nullable=True),
    sa.Column('order_amount_meters', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=True),
    sa.Column('currency', _upholstery_currency_enum, nullable=True),
    sa.Column('order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', _upholstery_order_state_enum, nullable=False),
    sa.Column('ordered_by_id', sa.String(length=64), nullable=True),
    sa.Column('expected_receive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_amount_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('order_amount_meters >= 0', name='ck_upholstery_orders_amount_positive'),
    sa.CheckConstraint('price_minor IS NULL OR price_minor >= 0', name='ck_upholstery_orders_price_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_inventory_id'], ['upholstery_inventory.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_supplier_link_id'], ['upholstery_supplier_links.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_upholstery_orders_created_by_id'), 'upholstery_orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholstery_orders_supplier_id'), 'upholstery_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_upholstery_orders_upholstery_inventory_id'), 'upholstery_orders', ['upholstery_inventory_id'], unique=False)
    op.create_index(op.f('ix_upholstery_orders_upholstery_supplier_link_id'), 'upholstery_orders', ['upholstery_supplier_link_id'], unique=False)
    op.create_index(op.f('ix_upholstery_orders_workspace_id'), 'upholstery_orders', ['workspace_id'], unique=False)
    op.create_index('ix_upholstery_orders_workspace_state_created', 'upholstery_orders', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_table('upholstery_order_history_records',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_order_id', sa.String(length=64), nullable=False),
    sa.Column('state', _upholstery_order_state_enum, nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('snapshot_price_minor', sa.Integer(), nullable=True),
    sa.Column('snapshot_currency', _upholstery_currency_enum, nullable=True),
    sa.Column('snapshot_order_amount_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('snapshot_order_amount_meters IS NULL OR snapshot_order_amount_meters >= 0', name='ck_upholstery_order_history_records_snapshot_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_order_id'], ['upholstery_orders.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_upholstery_order_history_records_created_by_id'), 'upholstery_order_history_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholstery_order_history_records_upholstery_order_id'), 'upholstery_order_history_records', ['upholstery_order_id'], unique=False)
    op.create_index(op.f('ix_upholstery_order_history_records_workspace_id'), 'upholstery_order_history_records', ['workspace_id'], unique=False)
    op.create_index('ix_upholstery_order_history_records_workspace_order_changed', 'upholstery_order_history_records', ['workspace_id', 'upholstery_order_id', 'changed_at'], unique=False)
    op.drop_constraint('history_records_created_by_id_fkey', 'history_records', type_='foreignkey')
    op.create_foreign_key(None, 'history_records', 'users', ['created_by_id'], ['client_id'], deferrable=True)
    op.alter_column('item_issues', 'step_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('item_issues', 'worker_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('item_issues', 'working_section_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('item_issues', 'item_category_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('item_issues', 'issue_type_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('item_issues', 'intensity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_issues', 'intensity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item_issues', 'issue_type_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('item_issues', 'item_category_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('item_issues', 'working_section_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('item_issues', 'worker_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('item_issues', 'step_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'history_records', type_='foreignkey')
    op.create_foreign_key('history_records_created_by_id_fkey', 'history_records', 'users', ['created_by_id'], ['client_id'], ondelete='RESTRICT', deferrable=True)
    op.drop_index('ix_upholstery_order_history_records_workspace_order_changed', table_name='upholstery_order_history_records')
    op.drop_index(op.f('ix_upholstery_order_history_records_workspace_id'), table_name='upholstery_order_history_records')
    op.drop_index(op.f('ix_upholstery_order_history_records_upholstery_order_id'), table_name='upholstery_order_history_records')
    op.drop_index(op.f('ix_upholstery_order_history_records_created_by_id'), table_name='upholstery_order_history_records')
    op.drop_table('upholstery_order_history_records')
    op.drop_index('ix_upholstery_orders_workspace_state_created', table_name='upholstery_orders')
    op.drop_index(op.f('ix_upholstery_orders_workspace_id'), table_name='upholstery_orders')
    op.drop_index(op.f('ix_upholstery_orders_upholstery_supplier_link_id'), table_name='upholstery_orders')
    op.drop_index(op.f('ix_upholstery_orders_upholstery_inventory_id'), table_name='upholstery_orders')
    op.drop_index(op.f('ix_upholstery_orders_supplier_id'), table_name='upholstery_orders')
    op.drop_index(op.f('ix_upholstery_orders_created_by_id'), table_name='upholstery_orders')
    op.drop_table('upholstery_orders')
    op.drop_index('ix_upholstery_supplier_links_workspace_upholstery_preferred', table_name='upholstery_supplier_links')
    op.drop_index(op.f('ix_upholstery_supplier_links_workspace_id'), table_name='upholstery_supplier_links')
    op.drop_index(op.f('ix_upholstery_supplier_links_upholstery_id'), table_name='upholstery_supplier_links')
    op.drop_index(op.f('ix_upholstery_supplier_links_supplier_id'), table_name='upholstery_supplier_links')
    op.drop_index(op.f('ix_upholstery_supplier_links_created_by_id'), table_name='upholstery_supplier_links')
    op.drop_table('upholstery_supplier_links')
    op.drop_index(op.f('ix_suppliers_workspace_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_by_id'), table_name='suppliers')
    op.drop_table('suppliers')
    _upholstery_order_state_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
