"""item_snapshot_columns_and_fix_unique_indexes

Revision ID: 3a5532f8f0a7
Revises: f3c8a1d209e5
Create Date: 2026-05-17 10:25:31.636037
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '3a5532f8f0a7'
down_revision: Union[str, None] = 'f3c8a1d209e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_category_snapshot', sa.String(length=255), nullable=True))
    op.add_column('items', sa.Column('item_major_category_snapshot', sa.String(length=64), nullable=True))
    op.drop_index('uix_items_workspace_article_number', table_name='items')
    op.drop_index('uix_items_workspace_sku', table_name='items')
    op.create_index(
        'uix_items_workspace_article_number',
        'items',
        ['workspace_id', 'article_number'],
        unique=True,
        postgresql_where=sa.text('article_number IS NOT NULL AND is_deleted = false'),
    )
    op.create_index(
        'uix_items_workspace_sku',
        'items',
        ['workspace_id', 'sku'],
        unique=True,
        postgresql_where=sa.text('sku IS NOT NULL AND is_deleted = false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_items_workspace_sku', table_name='items')
    op.drop_index('uix_items_workspace_article_number', table_name='items')
    op.create_index(
        'uix_items_workspace_sku',
        'items',
        ['workspace_id', 'sku'],
        unique=True,
        postgresql_where=sa.text('sku IS NOT NULL'),
    )
    op.create_index(
        'uix_items_workspace_article_number',
        'items',
        ['workspace_id', 'article_number'],
        unique=True,
        postgresql_where=sa.text('article_number IS NOT NULL'),
    )
    op.drop_column('items', 'item_major_category_snapshot')
    op.drop_column('items', 'item_category_snapshot')
    # ### end Alembic commands ###
