"""drop_redundant_index_user_lifetime_stats

Revision ID: 3b39a3884912
Revises: befad87b3463
Create Date: 2026-05-15 19:09:09.997111
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '3b39a3884912'
down_revision: Union[str, None] = 'befad87b3463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_lifetime_stats_workspace_user', table_name='user_lifetime_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_lifetime_stats_workspace_user', 'user_lifetime_stats', ['workspace_id', 'user_id'], unique=False)
    # ### end Alembic commands ###
