"""make_stock_report_versions_draftable

Draft versions (plan `update_stock_report/draft_versions_plan.md` §3.6). A version
gains a third, derived state — **draft** — so `active_at` becomes nullable on both
snapshot tables and the two "one active" partial unique indexes take the pair
`active_at IS NOT NULL AND closed_at IS NULL` as their predicate. An ordering group
becomes `(version_id, priority)`. The version gains `title`, a schedule and the
scheduled activation's missing flag; the snapshot's `quantity_requested` is
**renamed** `quantity_requested_scanner` and made nullable (NULL exactly while a
draft), `quantity_requested_manual` is added, and `quantity_missing` becomes
nullable (NULL only on a draft row nobody typed for). History records gain
`quantity_requested_source`.

Every existing row has `active_at = created_at` (verified against the create
command), so nothing is backfilled: every existing snapshot is activated, the renamed
column is non-null on each, and every new check holds on day one.

Hand-written, not autogenerated: `ALTER TYPE … ADD VALUE` is never autogenerated,
and the column rename must be a rename (autogenerate would drop and re-add). The
four `ADD VALUE`s are safe inside this transaction because nothing here uses the new
values (Postgres 12+). Enum values are never removed on downgrade (the
`11e1d0d47686` precedent).

Revision ID: 3b8d2f7a9c41
Revises: 2f7a9c3e5b1d
Create Date: 2026-09-28 18:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3b8d2f7a9c41"
down_revision: Union[str, None] = "2f7a9c3e5b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_VERSIONS = "stock_report_snapshot_versions"
_SNAPSHOTS = "stock_report_item_snapshots"
_HISTORY = "stock_report_history_records"

_OPEN = "closed_at IS NULL"
_ACTIVE = "active_at IS NOT NULL AND closed_at IS NULL"

_SOURCE_ENUM = postgresql.ENUM(
    "scanner",
    "manual",
    name="stock_report_quantity_requested_source_enum",
    create_type=False,
)


def upgrade() -> None:
    # 1. `active_at` nullable on both tables (instant).
    op.alter_column(
        _VERSIONS,
        "active_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        _SNAPSHOTS,
        "active_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )

    # 2. One active version per workspace — predicate on the pair.
    op.drop_index(
        "uix_stock_report_snapshot_versions_active",
        table_name=_VERSIONS,
        postgresql_where=sa.text(_OPEN),
    )
    op.create_index(
        "uix_stock_report_snapshot_versions_active",
        _VERSIONS,
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text(_ACTIVE),
    )

    # 3. One active snapshot per row — same predicate.
    op.drop_index(
        "uix_stock_report_item_snapshots_row_active",
        table_name=_SNAPSHOTS,
        postgresql_where=sa.text(_OPEN),
    )
    op.create_index(
        "uix_stock_report_item_snapshots_row_active",
        _SNAPSHOTS,
        ["workspace_id", "stock_report_item_id"],
        unique=True,
        postgresql_where=sa.text(_ACTIVE),
    )

    # 4. The ordering group is `(version_id, priority)`.
    op.drop_index(
        "ix_stock_report_item_snapshots_workspace_priority_order",
        table_name=_SNAPSHOTS,
        postgresql_where=sa.text(_OPEN),
    )
    op.create_index(
        "ix_stock_report_item_snapshots_version_priority_order",
        _SNAPSHOTS,
        ["version_id", "priority", "priority_order"],
        unique=False,
        postgresql_where=sa.text(_OPEN),
    )

    # 5. Versions: title, schedule, the scheduled activation's missing flag, the
    #    two lifecycle checks, the creation-order index.
    op.add_column(_VERSIONS, sa.Column("title", sa.String(length=200), nullable=True))
    op.add_column(
        _VERSIONS,
        sa.Column("scheduled_activation_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        _VERSIONS,
        sa.Column(
            "scheduled_activation_keeps_active_missing",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_stock_report_snapshot_versions_closed_implies_activated",
        _VERSIONS,
        "closed_at IS NULL OR active_at IS NOT NULL",
    )
    op.create_check_constraint(
        "ck_stock_report_snapshot_versions_schedule_only_on_draft",
        _VERSIONS,
        "scheduled_activation_at IS NULL OR active_at IS NULL",
    )
    op.create_index(
        "ix_stock_report_snapshot_versions_workspace_created_at",
        _VERSIONS,
        ["workspace_id", "created_at"],
        unique=False,
    )

    # 6. Snapshots: the rename, the manual column, the nullable missing, the checks.
    op.alter_column(
        _SNAPSHOTS,
        "quantity_requested",
        new_column_name="quantity_requested_scanner",
        existing_type=sa.Integer(),
        existing_nullable=False,
        existing_server_default="0",
    )
    op.alter_column(
        _SNAPSHOTS,
        "quantity_requested_scanner",
        existing_type=sa.Integer(),
        nullable=True,
        server_default=None,
        existing_server_default="0",
    )
    op.execute(
        f"ALTER TABLE {_SNAPSHOTS} RENAME CONSTRAINT "
        "ck_stock_report_item_snapshots_quantity_requested_nonneg "
        "TO ck_stock_report_item_snapshots_quantity_requested_scanner_nonneg"
    )
    op.add_column(
        _SNAPSHOTS, sa.Column("quantity_requested_manual", sa.Integer(), nullable=True)
    )
    op.create_check_constraint(
        "ck_stock_report_item_snapshots_quantity_requested_manual_nonneg",
        _SNAPSHOTS,
        "quantity_requested_manual >= 0",
    )
    op.create_check_constraint(
        "ck_stock_report_item_snapshots_scanner_iff_activated",
        _SNAPSHOTS,
        "(quantity_requested_scanner IS NULL) = (active_at IS NULL)",
    )
    op.create_check_constraint(
        "ck_stock_report_item_snapshots_closed_implies_activated",
        _SNAPSHOTS,
        "closed_at IS NULL OR active_at IS NOT NULL",
    )
    op.alter_column(
        _SNAPSHOTS,
        "quantity_missing",
        existing_type=sa.Integer(),
        nullable=True,
        server_default=None,
        existing_server_default="0",
    )
    op.create_check_constraint(
        "ck_stock_report_item_snapshots_missing_set_once_activated",
        _SNAPSHOTS,
        "active_at IS NULL OR quantity_missing IS NOT NULL",
    )

    # 7. History: the source column and the override record type.
    _SOURCE_ENUM.create(op.get_bind(), checkfirst=True)
    op.add_column(
        _HISTORY,
        sa.Column(
            "quantity_requested_source",
            _SOURCE_ENUM,
            server_default="scanner",
            nullable=False,
        ),
    )
    op.execute(
        "ALTER TYPE stock_report_history_record_type_enum "
        "ADD VALUE IF NOT EXISTS 'quantity_requested_override'"
    )

    # 8. The scheduler, task and repair-target enum values the later steps use.
    op.execute(
        "ALTER TYPE delayed_scheduler_type_enum "
        "ADD VALUE IF NOT EXISTS 'stock_report_version_activation'"
    )
    op.execute(
        "ALTER TYPE task_type_enum "
        "ADD VALUE IF NOT EXISTS 'stock_report_version_activation'"
    )
    op.execute(
        "ALTER TYPE stock_report_repair_target_kind_enum "
        "ADD VALUE IF NOT EXISTS 'snapshot_version'"
    )


def downgrade() -> None:
    bind = op.get_bind()
    drafts = bind.execute(
        sa.text(f"SELECT count(*) FROM {_VERSIONS} WHERE active_at IS NULL")
    ).scalar()
    manual = bind.execute(
        sa.text(
            f"SELECT count(*) FROM {_SNAPSHOTS} "
            "WHERE quantity_requested_manual IS NOT NULL"
        )
    ).scalar()
    if drafts or manual:
        raise RuntimeError(
            "cannot downgrade 3b8d2f7a9c41: "
            f"{drafts} draft version(s) and {manual} manual requested value(s) have "
            "no home in the previous schema; delete the drafts and revert the "
            "manual values first"
        )

    # 8/7 (enum values stay; the source column and its type go).
    op.drop_column(_HISTORY, "quantity_requested_source")
    op.execute("DROP TYPE stock_report_quantity_requested_source_enum")

    # 6.
    op.drop_constraint(
        "ck_stock_report_item_snapshots_missing_set_once_activated",
        _SNAPSHOTS,
        type_="check",
    )
    op.alter_column(
        _SNAPSHOTS,
        "quantity_missing",
        existing_type=sa.Integer(),
        nullable=False,
        server_default="0",
    )
    op.drop_constraint(
        "ck_stock_report_item_snapshots_closed_implies_activated",
        _SNAPSHOTS,
        type_="check",
    )
    op.drop_constraint(
        "ck_stock_report_item_snapshots_scanner_iff_activated",
        _SNAPSHOTS,
        type_="check",
    )
    op.drop_constraint(
        "ck_stock_report_item_snapshots_quantity_requested_manual_nonneg",
        _SNAPSHOTS,
        type_="check",
    )
    op.drop_column(_SNAPSHOTS, "quantity_requested_manual")
    op.execute(
        f"ALTER TABLE {_SNAPSHOTS} RENAME CONSTRAINT "
        "ck_stock_report_item_snapshots_quantity_requested_scanner_nonneg "
        "TO ck_stock_report_item_snapshots_quantity_requested_nonneg"
    )
    op.alter_column(
        _SNAPSHOTS,
        "quantity_requested_scanner",
        existing_type=sa.Integer(),
        nullable=False,
        server_default="0",
    )
    op.alter_column(
        _SNAPSHOTS,
        "quantity_requested_scanner",
        new_column_name="quantity_requested",
        existing_type=sa.Integer(),
        existing_nullable=False,
        existing_server_default="0",
    )

    # 5.
    op.drop_index(
        "ix_stock_report_snapshot_versions_workspace_created_at", table_name=_VERSIONS
    )
    op.drop_constraint(
        "ck_stock_report_snapshot_versions_schedule_only_on_draft",
        _VERSIONS,
        type_="check",
    )
    op.drop_constraint(
        "ck_stock_report_snapshot_versions_closed_implies_activated",
        _VERSIONS,
        type_="check",
    )
    op.drop_column(_VERSIONS, "scheduled_activation_keeps_active_missing")
    op.drop_column(_VERSIONS, "scheduled_activation_at")
    op.drop_column(_VERSIONS, "title")

    # 4.
    op.drop_index(
        "ix_stock_report_item_snapshots_version_priority_order",
        table_name=_SNAPSHOTS,
        postgresql_where=sa.text(_OPEN),
    )
    op.create_index(
        "ix_stock_report_item_snapshots_workspace_priority_order",
        _SNAPSHOTS,
        ["workspace_id", "priority", "priority_order"],
        unique=False,
        postgresql_where=sa.text(_OPEN),
    )

    # 3 / 2.
    op.drop_index(
        "uix_stock_report_item_snapshots_row_active",
        table_name=_SNAPSHOTS,
        postgresql_where=sa.text(_ACTIVE),
    )
    op.create_index(
        "uix_stock_report_item_snapshots_row_active",
        _SNAPSHOTS,
        ["workspace_id", "stock_report_item_id"],
        unique=True,
        postgresql_where=sa.text(_OPEN),
    )
    op.drop_index(
        "uix_stock_report_snapshot_versions_active",
        table_name=_VERSIONS,
        postgresql_where=sa.text(_ACTIVE),
    )
    op.create_index(
        "uix_stock_report_snapshot_versions_active",
        _VERSIONS,
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text(_OPEN),
    )

    # 1. No draft exists (checked above), so NOT NULL holds.
    op.alter_column(
        _SNAPSHOTS,
        "active_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.alter_column(
        _VERSIONS,
        "active_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
