"""create_user_declared_state_records_table

Revision ID: 595e7b840926
Revises: d8e4f1a2c6b7
Create Date: 2026-07-29 15:53:50.857146
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '595e7b840926'
down_revision: Union[str, None] = 'd8e4f1a2c6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_declared_state_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('pause_reason_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('closed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('exited_at IS NULL OR exited_at >= entered_at', name='ck_user_declared_state_records_exited_after_entered'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pause_reason_id'], ['pause_reasons.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_user_declared_state_records_pause_reason_id'), 'user_declared_state_records', ['pause_reason_id'], unique=False)
    op.create_index(op.f('ix_user_declared_state_records_user_id'), 'user_declared_state_records', ['user_id'], unique=False)
    op.create_index('ix_user_declared_state_records_user_workspace_entered', 'user_declared_state_records', ['user_id', 'workspace_id', 'entered_at'], unique=False)
    op.create_index(op.f('ix_user_declared_state_records_workspace_id'), 'user_declared_state_records', ['workspace_id'], unique=False)
    op.create_index('ix_user_declared_state_records_workspace_reason', 'user_declared_state_records', ['workspace_id', 'pause_reason_id'], unique=False)
    op.create_index('uix_user_declared_state_records_active', 'user_declared_state_records', ['user_id', 'workspace_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_user_declared_state_records_active', table_name='user_declared_state_records', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_index('ix_user_declared_state_records_workspace_reason', table_name='user_declared_state_records')
    op.drop_index(op.f('ix_user_declared_state_records_workspace_id'), table_name='user_declared_state_records')
    op.drop_index('ix_user_declared_state_records_user_workspace_entered', table_name='user_declared_state_records')
    op.drop_index(op.f('ix_user_declared_state_records_user_id'), table_name='user_declared_state_records')
    op.drop_index(op.f('ix_user_declared_state_records_pause_reason_id'), table_name='user_declared_state_records')
    op.drop_table('user_declared_state_records')
    # ### end Alembic commands ###
