"""create_shopify_integration_foundation

Revision ID: 677ed7131bb2
Revises: b2c4d6e8f0a1
Create Date: 2026-07-08 08:31:12.919913
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '677ed7131bb2'
down_revision: Union[str, None] = 'b2c4d6e8f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

shopify_integration_event_severity_enum = postgresql.ENUM(
    "info",
    "warning",
    "error",
    name="shopify_integration_event_severity_enum",
    create_type=False,
)
shopify_integration_event_type_enum = postgresql.ENUM(
    "install",
    "reauthorize",
    "webhook_sync",
    "webhook_received",
    "webhook_processed",
    "health_check",
    "error",
    name="shopify_integration_event_type_enum",
    create_type=False,
)
shopify_integration_status_enum = postgresql.ENUM(
    "pending_install",
    "active",
    "needs_reauth",
    "scopes_outdated",
    "webhooks_outdated",
    "disabled",
    "uninstalled",
    "error",
    name="shopify_integration_status_enum",
    create_type=False,
)
shopify_oauth_state_status_enum = postgresql.ENUM(
    "pending",
    "consumed",
    "expired",
    name="shopify_oauth_state_status_enum",
    create_type=False,
)
shopify_webhook_intake_status_enum = postgresql.ENUM(
    "received",
    "processing",
    "processed",
    "failed",
    "ignored",
    name="shopify_webhook_intake_status_enum",
    create_type=False,
)
shopify_webhook_payload_format_enum = postgresql.ENUM(
    "json",
    name="shopify_webhook_payload_format_enum",
    create_type=False,
)
shopify_webhook_subscription_status_enum = postgresql.ENUM(
    "pending",
    "active",
    "failed",
    "disabled",
    "removed",
    name="shopify_webhook_subscription_status_enum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_oauth_states',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'consumed', 'expired', name='shopify_oauth_state_status_enum'), server_default='pending', nullable=False),
    sa.Column('requested_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redirect_after_success', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('state', name='uq_shopify_oauth_states_state')
    )
    op.create_index('ix_shopify_oauth_states_consumed_at', 'shopify_oauth_states', ['consumed_at'], unique=False)
    op.create_index('ix_shopify_oauth_states_expires_at', 'shopify_oauth_states', ['expires_at'], unique=False)
    op.create_index('ix_shopify_oauth_states_shop_domain', 'shopify_oauth_states', ['shop_domain'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_status'), 'shopify_oauth_states', ['status'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_user_id'), 'shopify_oauth_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_shopify_oauth_states_workspace_id'), 'shopify_oauth_states', ['workspace_id'], unique=False)
    op.create_index('ix_shopify_oauth_states_workspace_user', 'shopify_oauth_states', ['workspace_id', 'user_id'], unique=False)
    op.create_table('shopify_shop_integrations',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), server_default='shopify', nullable=False),
    sa.Column('status', sa.Enum('pending_install', 'active', 'needs_reauth', 'scopes_outdated', 'webhooks_outdated', 'disabled', 'uninstalled', 'error', name='shopify_integration_status_enum'), server_default='pending_install', nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_version', sa.String(length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_status', sa.String(length=64), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_shopify_shop_integrations_created_at', 'shopify_shop_integrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_shopify_shop_integrations_created_by_id'), 'shopify_shop_integrations', ['created_by_id'], unique=False)
    op.create_index('ix_shopify_shop_integrations_is_deleted', 'shopify_shop_integrations', ['is_deleted'], unique=False)
    op.create_index('ix_shopify_shop_integrations_shop_domain_status', 'shopify_shop_integrations', ['shop_domain', 'status'], unique=False)
    op.create_index(op.f('ix_shopify_shop_integrations_status'), 'shopify_shop_integrations', ['status'], unique=False)
    op.create_index(op.f('ix_shopify_shop_integrations_workspace_id'), 'shopify_shop_integrations', ['workspace_id'], unique=False)
    op.create_index('ix_shopify_shop_integrations_workspace_status', 'shopify_shop_integrations', ['workspace_id', 'status'], unique=False)
    op.create_index('uix_shopify_shop_integrations_shop_domain_active', 'shopify_shop_integrations', ['shop_domain'], unique=True, postgresql_where=sa.text("is_deleted = false AND status IN ('pending_install', 'active', 'needs_reauth', 'scopes_outdated', 'webhooks_outdated', 'error')"))
    op.create_index('uix_shopify_shop_integrations_workspace_shop_domain_active', 'shopify_shop_integrations', ['workspace_id', 'shop_domain'], unique=True, postgresql_where=sa.text("is_deleted = false AND status IN ('pending_install', 'active', 'needs_reauth', 'scopes_outdated', 'webhooks_outdated', 'error')"))
    op.create_table('shopify_integration_events',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('shop_integration_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('install', 'reauthorize', 'webhook_sync', 'webhook_received', 'webhook_processed', 'health_check', 'error', name='shopify_integration_event_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='shopify_integration_event_severity_enum'), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_integration_id'], ['shopify_shop_integrations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_shopify_integration_events_created_at', 'shopify_integration_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_shopify_integration_events_created_by_id'), 'shopify_integration_events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_shopify_integration_events_event_type'), 'shopify_integration_events', ['event_type'], unique=False)
    op.create_index('ix_shopify_integration_events_severity', 'shopify_integration_events', ['severity'], unique=False)
    op.create_index(op.f('ix_shopify_integration_events_shop_integration_id'), 'shopify_integration_events', ['shop_integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_integration_events_workspace_id'), 'shopify_integration_events', ['workspace_id'], unique=False)
    op.create_index('ix_shopify_integration_events_workspace_shop_integration', 'shopify_integration_events', ['workspace_id', 'shop_integration_id'], unique=False)
    op.create_table('shopify_webhook_intakes',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('shop_integration_id', sa.String(length=64), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'processed', 'failed', 'ignored', name='shopify_webhook_intake_status_enum'), server_default='received', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retryable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_integration_id'], ['shopify_shop_integrations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('dedupe_key', name='uq_shopify_webhook_intakes_dedupe_key')
    )
    op.create_index('ix_shopify_webhook_intakes_received_at', 'shopify_webhook_intakes', ['received_at'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_intakes_shop_integration_id'), 'shopify_webhook_intakes', ['shop_integration_id'], unique=False)
    op.create_index('ix_shopify_webhook_intakes_shop_integration_topic', 'shopify_webhook_intakes', ['shop_integration_id', 'topic'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_intakes_status'), 'shopify_webhook_intakes', ['status'], unique=False)
    op.create_index('ix_shopify_webhook_intakes_webhook_id', 'shopify_webhook_intakes', ['webhook_id'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_intakes_workspace_id'), 'shopify_webhook_intakes', ['workspace_id'], unique=False)
    op.create_index('ix_shopify_webhook_intakes_workspace_status', 'shopify_webhook_intakes', ['workspace_id', 'status'], unique=False)
    op.create_table('shopify_webhook_subscriptions',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('shop_integration_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('remote_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('payload_format', sa.Enum('json', name='shopify_webhook_payload_format_enum'), server_default='json', nullable=False),
    sa.Column('required_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'failed', 'disabled', 'removed', name='shopify_webhook_subscription_status_enum'), server_default='pending', nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_install_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_integration_id'], ['shopify_shop_integrations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('shop_integration_id', 'topic', name='uq_shopify_webhook_subscriptions_shop_integration_topic')
    )
    op.create_index('ix_shopify_webhook_subscriptions_remote_subscription_id', 'shopify_webhook_subscriptions', ['remote_subscription_id'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_subscriptions_shop_integration_id'), 'shopify_webhook_subscriptions', ['shop_integration_id'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_subscriptions_status'), 'shopify_webhook_subscriptions', ['status'], unique=False)
    op.create_index('ix_shopify_webhook_subscriptions_topic_status', 'shopify_webhook_subscriptions', ['topic', 'status'], unique=False)
    op.create_index(op.f('ix_shopify_webhook_subscriptions_workspace_id'), 'shopify_webhook_subscriptions', ['workspace_id'], unique=False)
    op.create_index('ix_shopify_webhook_subscriptions_workspace_shop_integration', 'shopify_webhook_subscriptions', ['workspace_id', 'shop_integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopify_webhook_subscriptions_workspace_shop_integration', table_name='shopify_webhook_subscriptions')
    op.drop_index(op.f('ix_shopify_webhook_subscriptions_workspace_id'), table_name='shopify_webhook_subscriptions')
    op.drop_index('ix_shopify_webhook_subscriptions_topic_status', table_name='shopify_webhook_subscriptions')
    op.drop_index(op.f('ix_shopify_webhook_subscriptions_status'), table_name='shopify_webhook_subscriptions')
    op.drop_index(op.f('ix_shopify_webhook_subscriptions_shop_integration_id'), table_name='shopify_webhook_subscriptions')
    op.drop_index('ix_shopify_webhook_subscriptions_remote_subscription_id', table_name='shopify_webhook_subscriptions')
    op.drop_table('shopify_webhook_subscriptions')
    op.drop_index('ix_shopify_webhook_intakes_workspace_status', table_name='shopify_webhook_intakes')
    op.drop_index(op.f('ix_shopify_webhook_intakes_workspace_id'), table_name='shopify_webhook_intakes')
    op.drop_index('ix_shopify_webhook_intakes_webhook_id', table_name='shopify_webhook_intakes')
    op.drop_index(op.f('ix_shopify_webhook_intakes_status'), table_name='shopify_webhook_intakes')
    op.drop_index('ix_shopify_webhook_intakes_shop_integration_topic', table_name='shopify_webhook_intakes')
    op.drop_index(op.f('ix_shopify_webhook_intakes_shop_integration_id'), table_name='shopify_webhook_intakes')
    op.drop_index('ix_shopify_webhook_intakes_received_at', table_name='shopify_webhook_intakes')
    op.drop_table('shopify_webhook_intakes')
    op.drop_index('ix_shopify_integration_events_workspace_shop_integration', table_name='shopify_integration_events')
    op.drop_index(op.f('ix_shopify_integration_events_workspace_id'), table_name='shopify_integration_events')
    op.drop_index(op.f('ix_shopify_integration_events_shop_integration_id'), table_name='shopify_integration_events')
    op.drop_index('ix_shopify_integration_events_severity', table_name='shopify_integration_events')
    op.drop_index(op.f('ix_shopify_integration_events_event_type'), table_name='shopify_integration_events')
    op.drop_index(op.f('ix_shopify_integration_events_created_by_id'), table_name='shopify_integration_events')
    op.drop_index('ix_shopify_integration_events_created_at', table_name='shopify_integration_events')
    op.drop_table('shopify_integration_events')
    op.drop_index('uix_shopify_shop_integrations_workspace_shop_domain_active', table_name='shopify_shop_integrations', postgresql_where=sa.text("is_deleted = false AND status IN ('pending_install', 'active', 'needs_reauth', 'scopes_outdated', 'webhooks_outdated', 'error')"))
    op.drop_index('uix_shopify_shop_integrations_shop_domain_active', table_name='shopify_shop_integrations', postgresql_where=sa.text("is_deleted = false AND status IN ('pending_install', 'active', 'needs_reauth', 'scopes_outdated', 'webhooks_outdated', 'error')"))
    op.drop_index('ix_shopify_shop_integrations_workspace_status', table_name='shopify_shop_integrations')
    op.drop_index(op.f('ix_shopify_shop_integrations_workspace_id'), table_name='shopify_shop_integrations')
    op.drop_index(op.f('ix_shopify_shop_integrations_status'), table_name='shopify_shop_integrations')
    op.drop_index('ix_shopify_shop_integrations_shop_domain_status', table_name='shopify_shop_integrations')
    op.drop_index('ix_shopify_shop_integrations_is_deleted', table_name='shopify_shop_integrations')
    op.drop_index(op.f('ix_shopify_shop_integrations_created_by_id'), table_name='shopify_shop_integrations')
    op.drop_index('ix_shopify_shop_integrations_created_at', table_name='shopify_shop_integrations')
    op.drop_table('shopify_shop_integrations')
    op.drop_index('ix_shopify_oauth_states_workspace_user', table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_workspace_id'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_user_id'), table_name='shopify_oauth_states')
    op.drop_index(op.f('ix_shopify_oauth_states_status'), table_name='shopify_oauth_states')
    op.drop_index('ix_shopify_oauth_states_shop_domain', table_name='shopify_oauth_states')
    op.drop_index('ix_shopify_oauth_states_expires_at', table_name='shopify_oauth_states')
    op.drop_index('ix_shopify_oauth_states_consumed_at', table_name='shopify_oauth_states')
    op.drop_table('shopify_oauth_states')
    shopify_webhook_subscription_status_enum.drop(op.get_bind(), checkfirst=True)
    shopify_webhook_payload_format_enum.drop(op.get_bind(), checkfirst=True)
    shopify_webhook_intake_status_enum.drop(op.get_bind(), checkfirst=True)
    shopify_integration_event_severity_enum.drop(op.get_bind(), checkfirst=True)
    shopify_integration_event_type_enum.drop(op.get_bind(), checkfirst=True)
    shopify_integration_status_enum.drop(op.get_bind(), checkfirst=True)
    shopify_oauth_state_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
