"""add_clock_in_code_to_user_work_profiles

Revision ID: 67cfba8fcb2d
Revises: c2f4a6b8d0e1
Create Date: 2026-07-30 14:21:44.666282
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '67cfba8fcb2d'
down_revision: Union[str, None] = 'c2f4a6b8d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated, then trimmed: alembic also swept in pre-existing schema drift
    # unrelated to this phase (email_sync_states unique constraint, two
    # step_state_records indexes that exist in the DB but not in the models).
    # Acting on that drift here would be destructive and out of scope — the
    # declared-worker-states baseline (MASTER_PLAN, "Repository validation
    # baseline") owns it as separate repo-health work.
    op.add_column('user_work_profiles', sa.Column('clock_in_code', sa.String(length=16), nullable=True))
    op.create_index('uix_user_work_profiles_workspace_clock_code', 'user_work_profiles', ['workspace_id', 'clock_in_code'], unique=True, postgresql_where=sa.text('clock_in_code IS NOT NULL'))


def downgrade() -> None:
    op.drop_index('uix_user_work_profiles_workspace_clock_code', table_name='user_work_profiles', postgresql_where=sa.text('clock_in_code IS NOT NULL'))
    op.drop_column('user_work_profiles', 'clock_in_code')
