"""create_app_update_presentation_tables

Revision ID: 6b4a1295bb07
Revises: d0f2a3b4c5d6
Create Date: 2026-07-21 23:02:52.636354
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '6b4a1295bb07'
down_revision: Union[str, None] = 'd0f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_update_presentations',
    sa.Column('logical_client_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='app_update_presentation_status_enum'), nullable=False),
    sa.Column('presentation_type', sa.Enum('modal', 'full_screen', 'slide_page', name='app_update_presentation_type_enum'), nullable=False),
    sa.Column('audience_mode', sa.Enum('all_matching', 'selected_users_only', name='app_update_presentation_audience_mode_enum'), nullable=False),
    sa.Column('display_priority', sa.Integer(), nullable=False),
    sa.Column('is_dismissible', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('logical_client_id', 'version', name='uq_app_update_presentations_logical_version')
    )
    op.create_index(op.f('ix_app_update_presentations_created_by_id'), 'app_update_presentations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_app_update_presentations_display_priority'), 'app_update_presentations', ['display_priority'], unique=False)
    op.create_index(op.f('ix_app_update_presentations_logical_client_id'), 'app_update_presentations', ['logical_client_id'], unique=False)
    op.create_index(op.f('ix_app_update_presentations_status'), 'app_update_presentations', ['status'], unique=False)
    op.create_index(op.f('ix_app_update_presentations_workspace_id'), 'app_update_presentations', ['workspace_id'], unique=False)
    op.create_index('ix_app_update_presentations_ws_status_priority', 'app_update_presentations', ['workspace_id', 'status', 'display_priority'], unique=False)
    op.create_index('uix_app_update_presentations_one_published', 'app_update_presentations', ['logical_client_id'], unique=True, postgresql_where=sa.text("status = 'published' AND is_deleted = false"))
    op.create_table('app_update_presentation_app_targets',
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('app_key', sa.Enum('manager', 'worker', 'seller', 'admin', name='app_update_app_key_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'app_key', name='uq_app_update_app_targets_presentation_app')
    )
    op.create_index(op.f('ix_app_update_presentation_app_targets_presentation_id'), 'app_update_presentation_app_targets', ['presentation_id'], unique=False)
    op.create_table('app_update_presentation_role_targets',
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('role_key', sa.Enum('admin', 'worker', 'manager', 'seller', name='app_update_role_key_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'role_key', name='uq_app_update_role_targets_presentation_role')
    )
    op.create_index(op.f('ix_app_update_presentation_role_targets_presentation_id'), 'app_update_presentation_role_targets', ['presentation_id'], unique=False)
    op.create_table('app_update_presentation_slides',
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('layout_type', sa.Enum('media_top', 'media_full', 'text_overlay', name='app_update_slide_layout_enum'), nullable=False),
    sa.Column('action_label', sa.String(length=120), nullable=True),
    sa.Column('action_route', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'sequence_order', name='uq_app_update_slides_presentation_sequence')
    )
    op.create_index(op.f('ix_app_update_presentation_slides_presentation_id'), 'app_update_presentation_slides', ['presentation_id'], unique=False)
    op.create_index('ix_app_update_slides_presentation_sequence', 'app_update_presentation_slides', ['presentation_id', 'sequence_order'], unique=False)
    op.create_table('app_update_presentation_user_targets',
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'user_id', name='uq_app_update_user_targets_presentation_user')
    )
    op.create_index(op.f('ix_app_update_presentation_user_targets_presentation_id'), 'app_update_presentation_user_targets', ['presentation_id'], unique=False)
    op.create_index(op.f('ix_app_update_presentation_user_targets_user_id'), 'app_update_presentation_user_targets', ['user_id'], unique=False)
    op.create_table('app_update_presentation_views',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('acting_user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('shown', 'dismissed', 'completed', name='app_update_presentation_view_status_enum'), nullable=False),
    sa.Column('first_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_slide_index', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['acting_user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'acting_user_id', name='uq_app_update_presentation_views_presentation_user')
    )
    op.create_index(op.f('ix_app_update_presentation_views_acting_user_id'), 'app_update_presentation_views', ['acting_user_id'], unique=False)
    op.create_index(op.f('ix_app_update_presentation_views_presentation_id'), 'app_update_presentation_views', ['presentation_id'], unique=False)
    op.create_index('ix_app_update_presentation_views_user_incomplete', 'app_update_presentation_views', ['acting_user_id', 'presentation_id'], unique=False, postgresql_where=sa.text('completed_at IS NULL'))
    op.create_index(op.f('ix_app_update_presentation_views_workspace_id'), 'app_update_presentation_views', ['workspace_id'], unique=False)
    op.create_table('app_update_presentation_workspace_targets',
    sa.Column('presentation_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['app_update_presentations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('presentation_id', 'workspace_id', name='uq_app_update_workspace_targets_presentation_workspace')
    )
    op.create_index(op.f('ix_app_update_presentation_workspace_targets_presentation_id'), 'app_update_presentation_workspace_targets', ['presentation_id'], unique=False)
    op.create_index(op.f('ix_app_update_presentation_workspace_targets_workspace_id'), 'app_update_presentation_workspace_targets', ['workspace_id'], unique=False)
    op.create_table('app_update_slide_media',
    sa.Column('slide_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='app_update_slide_media_type_enum'), nullable=False),
    sa.Column('storage_key', sa.String(length=2048), nullable=False),
    sa.Column('poster_storage_key', sa.String(length=2048), nullable=True),
    sa.Column('fallback_storage_key', sa.String(length=2048), nullable=True),
    sa.Column('alt_text', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_looping', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['slide_id'], ['app_update_presentation_slides.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('slide_id', 'sequence_order', name='uq_app_update_slide_media_slide_sequence')
    )
    op.create_index(op.f('ix_app_update_slide_media_slide_id'), 'app_update_slide_media', ['slide_id'], unique=False)
    op.create_index('ix_app_update_slide_media_slide_sequence', 'app_update_slide_media', ['slide_id', 'sequence_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_update_slide_media_slide_sequence', table_name='app_update_slide_media')
    op.drop_index(op.f('ix_app_update_slide_media_slide_id'), table_name='app_update_slide_media')
    op.drop_table('app_update_slide_media')
    op.drop_index(op.f('ix_app_update_presentation_workspace_targets_workspace_id'), table_name='app_update_presentation_workspace_targets')
    op.drop_index(op.f('ix_app_update_presentation_workspace_targets_presentation_id'), table_name='app_update_presentation_workspace_targets')
    op.drop_table('app_update_presentation_workspace_targets')
    op.drop_index(op.f('ix_app_update_presentation_views_workspace_id'), table_name='app_update_presentation_views')
    op.drop_index('ix_app_update_presentation_views_user_incomplete', table_name='app_update_presentation_views', postgresql_where=sa.text('completed_at IS NULL'))
    op.drop_index(op.f('ix_app_update_presentation_views_presentation_id'), table_name='app_update_presentation_views')
    op.drop_index(op.f('ix_app_update_presentation_views_acting_user_id'), table_name='app_update_presentation_views')
    op.drop_table('app_update_presentation_views')
    op.drop_index(op.f('ix_app_update_presentation_user_targets_user_id'), table_name='app_update_presentation_user_targets')
    op.drop_index(op.f('ix_app_update_presentation_user_targets_presentation_id'), table_name='app_update_presentation_user_targets')
    op.drop_table('app_update_presentation_user_targets')
    op.drop_index('ix_app_update_slides_presentation_sequence', table_name='app_update_presentation_slides')
    op.drop_index(op.f('ix_app_update_presentation_slides_presentation_id'), table_name='app_update_presentation_slides')
    op.drop_table('app_update_presentation_slides')
    op.drop_index(op.f('ix_app_update_presentation_role_targets_presentation_id'), table_name='app_update_presentation_role_targets')
    op.drop_table('app_update_presentation_role_targets')
    op.drop_index(op.f('ix_app_update_presentation_app_targets_presentation_id'), table_name='app_update_presentation_app_targets')
    op.drop_table('app_update_presentation_app_targets')
    op.drop_index('uix_app_update_presentations_one_published', table_name='app_update_presentations', postgresql_where=sa.text("status = 'published' AND is_deleted = false"))
    op.drop_index('ix_app_update_presentations_ws_status_priority', table_name='app_update_presentations')
    op.drop_index(op.f('ix_app_update_presentations_workspace_id'), table_name='app_update_presentations')
    op.drop_index(op.f('ix_app_update_presentations_status'), table_name='app_update_presentations')
    op.drop_index(op.f('ix_app_update_presentations_logical_client_id'), table_name='app_update_presentations')
    op.drop_index(op.f('ix_app_update_presentations_display_priority'), table_name='app_update_presentations')
    op.drop_index(op.f('ix_app_update_presentations_created_by_id'), table_name='app_update_presentations')
    op.drop_table('app_update_presentations')
    op.execute("DROP TYPE IF EXISTS app_update_presentation_view_status_enum")
    op.execute("DROP TYPE IF EXISTS app_update_slide_media_type_enum")
    op.execute("DROP TYPE IF EXISTS app_update_slide_layout_enum")
    op.execute("DROP TYPE IF EXISTS app_update_role_key_enum")
    op.execute("DROP TYPE IF EXISTS app_update_app_key_enum")
    op.execute("DROP TYPE IF EXISTS app_update_presentation_audience_mode_enum")
    op.execute("DROP TYPE IF EXISTS app_update_presentation_type_enum")
    op.execute("DROP TYPE IF EXISTS app_update_presentation_status_enum")
    # ### end Alembic commands ###
