"""add_inaccurate_time_metrics

Revision ID: 74f152a8b9d1
Revises: a7f3c1e9d240
Create Date: 2026-07-18 20:49:36.717610
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '74f152a8b9d1'
down_revision: Union[str, None] = 'a7f3c1e9d240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FLAGGED_INDEX = "ix_step_state_records_ws_flagged_entered"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('inaccurate_working_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('task_steps', sa.Column('inaccurate_pause_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('task_steps', sa.Column('inaccurate_ended_shift_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_daily_work_stats', sa.Column('inaccurate_working_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_daily_work_stats', sa.Column('inaccurate_pause_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_daily_work_stats', sa.Column('inaccurate_ended_shift_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_daily_work_stats', sa.Column('inaccurate_step_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lifetime_stats', sa.Column('inaccurate_working_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lifetime_stats', sa.Column('inaccurate_pause_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lifetime_stats', sa.Column('inaccurate_ended_shift_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lifetime_stats', sa.Column('inaccurate_step_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_section_daily_work_stats', sa.Column('inaccurate_working_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_section_daily_work_stats', sa.Column('inaccurate_pause_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_section_daily_work_stats', sa.Column('inaccurate_ended_shift_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_section_daily_work_stats', sa.Column('inaccurate_step_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('working_section_daily_work_stats', sa.Column('inaccurate_working_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('working_section_daily_work_stats', sa.Column('inaccurate_pause_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('working_section_daily_work_stats', sa.Column('inaccurate_ended_shift_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('working_section_daily_work_stats', sa.Column('inaccurate_step_count', sa.Integer(), server_default='0', nullable=False))
    op.execute(
        f"CREATE INDEX {_FLAGGED_INDEX} ON step_state_records "
        "(workspace_id, COALESCE(credited_user_id, created_by_id), entered_at) "
        "WHERE recorded_time_marked_wrong"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('working_section_daily_work_stats', 'inaccurate_step_count')
    op.drop_column('working_section_daily_work_stats', 'inaccurate_ended_shift_seconds')
    op.drop_column('working_section_daily_work_stats', 'inaccurate_pause_seconds')
    op.drop_column('working_section_daily_work_stats', 'inaccurate_working_seconds')
    op.drop_column('user_section_daily_work_stats', 'inaccurate_step_count')
    op.drop_column('user_section_daily_work_stats', 'inaccurate_ended_shift_seconds')
    op.drop_column('user_section_daily_work_stats', 'inaccurate_pause_seconds')
    op.drop_column('user_section_daily_work_stats', 'inaccurate_working_seconds')
    op.drop_column('user_lifetime_stats', 'inaccurate_step_count')
    op.drop_column('user_lifetime_stats', 'inaccurate_ended_shift_seconds')
    op.drop_column('user_lifetime_stats', 'inaccurate_pause_seconds')
    op.drop_column('user_lifetime_stats', 'inaccurate_working_seconds')
    op.drop_column('user_daily_work_stats', 'inaccurate_step_count')
    op.drop_column('user_daily_work_stats', 'inaccurate_ended_shift_seconds')
    op.drop_column('user_daily_work_stats', 'inaccurate_pause_seconds')
    op.drop_column('user_daily_work_stats', 'inaccurate_working_seconds')
    op.drop_column('task_steps', 'inaccurate_ended_shift_seconds')
    op.drop_column('task_steps', 'inaccurate_pause_seconds')
    op.drop_column('task_steps', 'inaccurate_working_seconds')
    op.execute(f"DROP INDEX IF EXISTS {_FLAGGED_INDEX}")
    # ### end Alembic commands ###
