"""model creation for beyo-manager

Revision ID: 7d92a90e6282
Revises: a1312183fdfb
Create Date: 2026-05-15 12:11:40.542905
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '7d92a90e6282'
down_revision: Union[str, None] = 'a1312183fdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('customer_type', sa.Enum('PERSON', 'COMPANY', 'UNKNOWN', name='customer_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='customer_status_enum'), nullable=False),
    sa.Column('primary_phone_number', sa.String(length=64), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone_number_normalized', sa.String(length=64), nullable=True),
    sa.Column('primary_email_normalized', sa.String(length=255), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('latest_history_record_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_history_record_id'], ['customer_history_records.client_id'], name='fk_customers_latest_history_record_id', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_customers_created_by_id'), 'customers', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_customers_latest_history_record_id'), 'customers', ['latest_history_record_id'], unique=False)
    op.create_index(op.f('ix_customers_primary_email_normalized'), 'customers', ['primary_email_normalized'], unique=False)
    op.create_index(op.f('ix_customers_primary_phone_number_normalized'), 'customers', ['primary_phone_number_normalized'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index('ix_customers_workspace_display_name', 'customers', ['workspace_id', 'display_name'], unique=False)
    op.create_index('ix_customers_workspace_email', 'customers', ['workspace_id', 'primary_email'], unique=False)
    op.create_index('ix_customers_workspace_email_normalized', 'customers', ['workspace_id', 'primary_email_normalized'], unique=False)
    op.create_index(op.f('ix_customers_workspace_id'), 'customers', ['workspace_id'], unique=False)
    op.create_index('ix_customers_workspace_phone', 'customers', ['workspace_id', 'primary_phone_number'], unique=False)
    op.create_index('ix_customers_workspace_phone_normalized', 'customers', ['workspace_id', 'primary_phone_number_normalized'], unique=False)
    op.create_table('issue_severities',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('time_multiplier', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('time_multiplier >= 0', name='ck_issue_severities_time_multiplier_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_issue_severities_workspace_name')
    )
    op.create_index(op.f('ix_issue_severities_created_by_id'), 'issue_severities', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_issue_severities_workspace_id'), 'issue_severities', ['workspace_id'], unique=False)
    op.create_table('issue_types',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('INTERNAL_INSPECTION', 'CUSTOMER', 'SUPPLIER', 'IMPORTED', name='issue_source_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_issue_types_workspace_name')
    )
    op.create_index(op.f('ix_issue_types_created_by_id'), 'issue_types', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_issue_types_source'), 'issue_types', ['source'], unique=False)
    op.create_index(op.f('ix_issue_types_workspace_id'), 'issue_types', ['workspace_id'], unique=False)
    op.create_table('item_categories',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('major_category', sa.Enum('WOOD', 'SEAT', name='item_major_category_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_item_categories_workspace_name')
    )
    op.create_index(op.f('ix_item_categories_created_by_id'), 'item_categories', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_categories_major_category'), 'item_categories', ['major_category'], unique=False)
    op.create_index(op.f('ix_item_categories_workspace_id'), 'item_categories', ['workspace_id'], unique=False)
    op.create_index('ix_item_categories_workspace_major_category', 'item_categories', ['workspace_id', 'major_category'], unique=False)
    op.create_table('static_costs',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('cost_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('SWEDISH_KRONA', 'DANISH_KRONA', 'EURO', name='static_cost_currency_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_static_costs_created_by_id'), 'static_costs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_static_costs_workspace_id'), 'static_costs', ['workspace_id'], unique=False)
    op.create_table('upholsteries',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_upholsteries_workspace_name')
    )
    op.create_index(op.f('ix_upholsteries_created_by_id'), 'upholsteries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholsteries_workspace_id'), 'upholsteries', ['workspace_id'], unique=False)
    op.create_index('uix_upholsteries_workspace_code', 'upholsteries', ['workspace_id', 'code'], unique=True, postgresql_where=sa.text('code IS NOT NULL'))
    op.create_table('user_shift_state_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('STARTED_SHIFT', 'WORKING', 'IN_PAUSE', 'ENDED_SHIFT', name='user_shift_state_enum'), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('exited_at IS NULL OR exited_at >= entered_at', name='ck_user_shift_state_records_exited_after_entered'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_user_shift_state_records_user_id'), 'user_shift_state_records', ['user_id'], unique=False)
    op.create_index('ix_user_shift_state_records_user_workspace_entered', 'user_shift_state_records', ['user_id', 'workspace_id', 'entered_at'], unique=False)
    op.create_index('ix_user_shift_state_records_user_workspace_exited', 'user_shift_state_records', ['user_id', 'workspace_id', 'exited_at'], unique=False)
    op.create_index(op.f('ix_user_shift_state_records_workspace_id'), 'user_shift_state_records', ['workspace_id'], unique=False)
    op.create_index('uix_user_shift_state_records_active', 'user_shift_state_records', ['user_id', 'workspace_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_table('user_work_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('salary_per_hour_before_tax', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('salary_per_hour_after_tax', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('salary_per_hour_after_tax IS NULL OR salary_per_hour_after_tax >= 0', name='ck_user_work_profiles_salary_after_tax'),
    sa.CheckConstraint('salary_per_hour_before_tax IS NULL OR salary_per_hour_before_tax >= 0', name='ck_user_work_profiles_salary_before_tax'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_user_work_profiles_user_workspace')
    )
    op.create_index(op.f('ix_user_work_profiles_created_by_id'), 'user_work_profiles', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_user_work_profiles_user_id'), 'user_work_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_work_profiles_workspace_id'), 'user_work_profiles', ['workspace_id'], unique=False)
    op.create_index('ix_user_work_profiles_workspace_user', 'user_work_profiles', ['workspace_id', 'user_id'], unique=False)
    op.create_table('working_sections',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_working_sections_workspace_name')
    )
    op.create_index(op.f('ix_working_sections_created_by_id'), 'working_sections', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_working_sections_workspace_id'), 'working_sections', ['workspace_id'], unique=False)
    op.create_table('customer_history_records',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.Enum('CREATED', 'PROFILE_UPDATED', 'CONTACT_UPDATED', 'ADDRESS_UPDATED', 'STATUS_UPDATED', 'SOFT_DELETED', 'RESTORED', 'MERGED', 'REDACTED', 'ANONYMIZED', 'CORRECTION', 'RETRACTION', name='customer_history_change_type_enum'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.String(length=512), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_customer_history_records_change_type'), 'customer_history_records', ['change_type'], unique=False)
    op.create_index(op.f('ix_customer_history_records_created_by_id'), 'customer_history_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_customer_history_records_customer_id'), 'customer_history_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_history_records_occurred_at'), 'customer_history_records', ['occurred_at'], unique=False)
    op.create_index('ix_customer_history_records_workspace_customer_created', 'customer_history_records', ['workspace_id', 'customer_id', 'created_at'], unique=False)
    op.create_index('ix_customer_history_records_workspace_customer_occurred', 'customer_history_records', ['workspace_id', 'customer_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_customer_history_records_workspace_id'), 'customer_history_records', ['workspace_id'], unique=False)
    op.create_table('issue_category_configs',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('issue_type_id', sa.String(length=64), nullable=False),
    sa.Column('item_category_id', sa.String(length=64), nullable=False),
    sa.Column('base_time_seconds', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('base_time_seconds >= 0', name='ck_issue_category_configs_base_time_positive'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_issue_category_configs_effective_window'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'issue_type_id', 'item_category_id', 'effective_from', name='uq_issue_category_configs_unique')
    )
    op.create_index(op.f('ix_issue_category_configs_created_by_id'), 'issue_category_configs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_issue_category_configs_issue_type_id'), 'issue_category_configs', ['issue_type_id'], unique=False)
    op.create_index(op.f('ix_issue_category_configs_item_category_id'), 'issue_category_configs', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_issue_category_configs_workspace_id'), 'issue_category_configs', ['workspace_id'], unique=False)
    op.create_table('items',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('article_number', sa.String(length=128), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'STALL', 'FIXING', 'READY', name='item_state_enum'), nullable=False),
    sa.Column('item_category_id', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('designer', sa.String(length=255), nullable=True),
    sa.Column('height_in_cm', sa.Integer(), nullable=True),
    sa.Column('width_in_cm', sa.Integer(), nullable=True),
    sa.Column('depth_in_cm', sa.Integer(), nullable=True),
    sa.Column('item_value_minor', sa.Integer(), nullable=True),
    sa.Column('item_cost_minor', sa.Integer(), nullable=True),
    sa.Column('item_currency', sa.Enum('SWEDISH_KRONA', 'DANISH_KRONA', 'EURO', name='item_currency_enum'), nullable=True),
    sa.Column('item_position', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('external_source', sa.String(length=128), nullable=True),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_items_article_number'), 'items', ['article_number'], unique=False)
    op.create_index(op.f('ix_items_created_by_id'), 'items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_items_item_category_id'), 'items', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=False)
    op.create_index(op.f('ix_items_state'), 'items', ['state'], unique=False)
    op.create_index(op.f('ix_items_workspace_id'), 'items', ['workspace_id'], unique=False)
    op.create_index('ix_items_workspace_state', 'items', ['workspace_id', 'state'], unique=False)
    op.create_index('uix_items_workspace_article_number', 'items', ['workspace_id', 'article_number'], unique=True, postgresql_where=sa.text('article_number IS NOT NULL'))
    op.create_index('uix_items_workspace_sku', 'items', ['workspace_id', 'sku'], unique=True, postgresql_where=sa.text('sku IS NOT NULL'))
    op.create_table('tasks',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_scalar_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('RETURN', 'PRE_ORDER', 'INTERNAL', name='business_task_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='task_priority_enum'), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ASSIGNED', 'WORKING', 'STALLED', 'READY', 'RESOLVED', 'FAILED', 'CANCELLED', name='task_state_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('return_source', sa.Enum('AFTER_PURCHASE', 'BEFORE_PURCHASE', 'STORE_RETURN', name='task_return_source_enum'), nullable=True),
    sa.Column('item_location', sa.Enum('STORE', 'CUSTOMER', name='task_item_location_enum'), nullable=True),
    sa.Column('additional_details', sa.JSON(), nullable=True),
    sa.Column('ready_by_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_method', sa.Enum('DROP_OFF_BY_CUSTOMER', 'PICKUP', name='task_return_method_enum'), nullable=True),
    sa.Column('fulfillment_method', sa.Enum('PICKUP_AT_STORE', 'DELIVERY', name='task_fulfillment_method_enum'), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('primary_phone_number', sa.String(length=64), nullable=True),
    sa.Column('secondary_phone_number', sa.String(length=64), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('secondary_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_history_record_id', sa.String(length=64), nullable=True),
    sa.Column('latest_event_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('recorded_time_marked_wrong', sa.Boolean(), nullable=False),
    sa.Column('taken_from_average', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('scheduled_end_at IS NULL OR scheduled_start_at IS NULL OR scheduled_end_at >= scheduled_start_at', name='ck_tasks_scheduled_end_after_start'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_event_id'], ['task_events.client_id'], name='fk_tasks_latest_event_id', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['latest_history_record_id'], ['task_history_records.client_id'], name='fk_tasks_latest_history_record_id', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'task_scalar_id', name='uq_tasks_workspace_scalar_id')
    )
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_customer_id'), 'tasks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tasks_latest_event_id'), 'tasks', ['latest_event_id'], unique=False)
    op.create_index(op.f('ix_tasks_latest_history_record_id'), 'tasks', ['latest_history_record_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_state'), 'tasks', ['state'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_index('ix_tasks_workspace_state_scheduled_start', 'tasks', ['workspace_id', 'state', 'scheduled_start_at'], unique=False)
    op.create_table('upholstery_inventory',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_id', sa.String(length=64), nullable=False),
    sa.Column('minimum_to_have', sa.Integer(), nullable=True),
    sa.Column('maximum_to_have', sa.Integer(), nullable=True),
    sa.Column('projected_inventory_value_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Enum('SWEDISH_KRONA', 'DANISH_KRONA', 'EURO', name='upholstery_currency_enum'), nullable=True),
    sa.Column('planning_position', sa.String(length=255), nullable=True),
    sa.Column('inventory_condition', sa.Enum('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', name='upholstery_inventory_condition_enum'), nullable=False),
    sa.Column('current_stored_amount_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('current_amount_in_use_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('current_amount_in_need_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('current_amount_ordered_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_upholstery_used_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_upholstery_used_inventory_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_upholstery_used_surplus_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_upholstery_surplus_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('latest_projection_history_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('maximum_to_have IS NULL OR maximum_to_have >= 0', name='ck_upholstery_inventory_max_positive'),
    sa.CheckConstraint('maximum_to_have IS NULL OR minimum_to_have IS NULL OR maximum_to_have >= minimum_to_have', name='ck_upholstery_inventory_max_gte_min'),
    sa.CheckConstraint('minimum_to_have IS NULL OR minimum_to_have >= 0', name='ck_upholstery_inventory_min_positive'),
    sa.CheckConstraint('projected_inventory_value_minor IS NULL OR projected_inventory_value_minor >= 0', name='ck_upholstery_inventory_value_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_id'], ['upholsteries.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'upholstery_id', name='uq_upholstery_inventory_workspace_upholstery')
    )
    op.create_index(op.f('ix_upholstery_inventory_created_by_id'), 'upholstery_inventory', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_inventory_condition'), 'upholstery_inventory', ['inventory_condition'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_upholstery_id'), 'upholstery_inventory', ['upholstery_id'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_workspace_id'), 'upholstery_inventory', ['workspace_id'], unique=False)
    op.create_table('upholstery_inventory_threshold_policies',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Enum('WORKSPACE_DEFAULT', 'UPHOLSTERY', name='threshold_policy_scope_enum'), nullable=False),
    sa.Column('upholstery_id', sa.String(length=64), nullable=True),
    sa.Column('low_stock_minimum_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('low_stock_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('out_of_stock_epsilon_meters', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('escalation_policy', sa.Enum('NONE', 'RECOMMEND_REORDER', 'ESCALATE_TO_PROCUREMENT', name='sourcing_escalation_policy_enum'), nullable=True),
    sa.Column('warning_tier', sa.Enum('NORMAL', 'LOW_STOCK_WARNING', 'URGENT_REORDER', name='inventory_warning_tier_enum'), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("scope != 'UPHOLSTERY' OR upholstery_id IS NOT NULL", name='ck_utp_upholstery_scope_requires_id'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_utp_effective_window'),
    sa.CheckConstraint('low_stock_minimum_meters IS NULL OR low_stock_minimum_meters >= 0', name='ck_utp_low_stock_min_positive'),
    sa.CheckConstraint('low_stock_ratio IS NULL OR (low_stock_ratio >= 0 AND low_stock_ratio <= 1)', name='ck_utp_low_stock_ratio_range'),
    sa.CheckConstraint('out_of_stock_epsilon_meters IS NULL OR out_of_stock_epsilon_meters >= 0', name='ck_utp_epsilon_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_id'], ['upholsteries.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'scope', 'upholstery_id', 'effective_from', name='uq_upholstery_inv_threshold_policies_unique')
    )
    op.create_index(op.f('ix_upholstery_inventory_threshold_policies_created_by_id'), 'upholstery_inventory_threshold_policies', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_threshold_policies_scope'), 'upholstery_inventory_threshold_policies', ['scope'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_threshold_policies_upholstery_id'), 'upholstery_inventory_threshold_policies', ['upholstery_id'], unique=False)
    op.create_index(op.f('ix_upholstery_inventory_threshold_policies_workspace_id'), 'upholstery_inventory_threshold_policies', ['workspace_id'], unique=False)
    op.create_table('working_section_dependencies',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('dependent_section_id', sa.String(length=64), nullable=False),
    sa.Column('prerequisite_section_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('dependent_section_id != prerequisite_section_id', name='ck_working_section_dependencies_no_self_ref'),
    sa.ForeignKeyConstraint(['dependent_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prerequisite_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'dependent_section_id', 'prerequisite_section_id', name='uq_working_section_dependencies_unique_edge')
    )
    op.create_index(op.f('ix_working_section_dependencies_dependent_section_id'), 'working_section_dependencies', ['dependent_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_dependencies_prerequisite_section_id'), 'working_section_dependencies', ['prerequisite_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_dependencies_workspace_id'), 'working_section_dependencies', ['workspace_id'], unique=False)
    op.create_table('working_section_item_categories',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('item_category_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'working_section_id', 'item_category_id', name='uq_ws_item_categories_unique')
    )
    op.create_index(op.f('ix_working_section_item_categories_item_category_id'), 'working_section_item_categories', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_working_section_item_categories_working_section_id'), 'working_section_item_categories', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_item_categories_workspace_id'), 'working_section_item_categories', ['workspace_id'], unique=False)
    op.create_table('working_section_memberships',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=64), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_working_section_memberships_section_removed', 'working_section_memberships', ['working_section_id', 'removed_at'], unique=False)
    op.create_index(op.f('ix_working_section_memberships_user_id'), 'working_section_memberships', ['user_id'], unique=False)
    op.create_index('ix_working_section_memberships_user_removed', 'working_section_memberships', ['user_id', 'removed_at'], unique=False)
    op.create_index(op.f('ix_working_section_memberships_working_section_id'), 'working_section_memberships', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_memberships_workspace_id'), 'working_section_memberships', ['workspace_id'], unique=False)
    op.create_index('uix_working_section_memberships_active', 'working_section_memberships', ['workspace_id', 'working_section_id', 'user_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('working_section_supported_issue_types',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('issue_type_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'working_section_id', 'issue_type_id', name='uq_ws_supported_issue_types_unique')
    )
    op.create_index(op.f('ix_working_section_supported_issue_types_issue_type_id'), 'working_section_supported_issue_types', ['issue_type_id'], unique=False)
    op.create_index(op.f('ix_working_section_supported_issue_types_working_section_id'), 'working_section_supported_issue_types', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_supported_issue_types_workspace_id'), 'working_section_supported_issue_types', ['workspace_id'], unique=False)
    op.create_table('item_issues',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('issue_type_id', sa.String(length=64), nullable=True),
    sa.Column('issue_severity_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'FIXING', 'BLOCKED', 'DEFERRED', 'SKIPPED', 'RESOLVED', name='item_issue_state_enum'), nullable=False),
    sa.Column('base_time_seconds', sa.Integer(), nullable=True),
    sa.Column('time_multiplier', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('issue_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('severity_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('base_time_seconds IS NULL OR base_time_seconds >= 0', name='ck_item_issues_base_time_positive'),
    sa.CheckConstraint('time_multiplier IS NULL OR time_multiplier >= 0', name='ck_item_issues_time_multiplier_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_severity_id'], ['issue_severities.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_type_id'], ['issue_types.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_issues_created_by_id'), 'item_issues', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_issues_issue_severity_id'), 'item_issues', ['issue_severity_id'], unique=False)
    op.create_index(op.f('ix_item_issues_issue_type_id'), 'item_issues', ['issue_type_id'], unique=False)
    op.create_index(op.f('ix_item_issues_item_id'), 'item_issues', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_issues_state'), 'item_issues', ['state'], unique=False)
    op.create_index(op.f('ix_item_issues_workspace_id'), 'item_issues', ['workspace_id'], unique=False)
    op.create_index('ix_item_issues_workspace_item_state', 'item_issues', ['workspace_id', 'item_id', 'state'], unique=False)
    op.create_index('ix_item_issues_workspace_state', 'item_issues', ['workspace_id', 'state'], unique=False)
    op.create_table('item_upholsteries',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('amount_meters', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('source', sa.Enum('INTERNAL', 'CUSTOMER', name='item_upholstery_source_enum'), nullable=False),
    sa.Column('time_to_fix_in_seconds', sa.Integer(), nullable=True),
    sa.Column('active_requirement_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('amount_meters IS NULL OR amount_meters >= 0', name='ck_item_upholsteries_amount_positive'),
    sa.CheckConstraint('time_to_fix_in_seconds IS NULL OR time_to_fix_in_seconds >= 0', name='ck_item_upholsteries_time_positive'),
    sa.ForeignKeyConstraint(['active_requirement_id'], ['item_upholstery_requirements.client_id'], name='fk_item_upholsteries_active_requirement_id', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_id'], ['upholsteries.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_upholsteries_active_requirement_id'), 'item_upholsteries', ['active_requirement_id'], unique=False)
    op.create_index(op.f('ix_item_upholsteries_created_by_id'), 'item_upholsteries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_upholsteries_item_id'), 'item_upholsteries', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_upholsteries_source'), 'item_upholsteries', ['source'], unique=False)
    op.create_index(op.f('ix_item_upholsteries_upholstery_id'), 'item_upholsteries', ['upholstery_id'], unique=False)
    op.create_index(op.f('ix_item_upholsteries_workspace_id'), 'item_upholsteries', ['workspace_id'], unique=False)
    op.create_index('ix_item_upholsteries_workspace_item', 'item_upholsteries', ['workspace_id', 'item_id'], unique=False)
    op.create_table('task_events',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_STATE_CHANGED', 'TASK_STEP_STATE_CHANGED', 'TASK_ASSIGNMENT_CHANGED', 'TASK_RESOLVED', name='task_event_type_enum'), nullable=False),
    sa.Column('event_lifecycle_state', sa.Enum('RECORDED', 'SUPERSEDED', 'COMPENSATED', 'IGNORED', name='task_domain_event_lifecycle_state_enum'), nullable=False),
    sa.Column('error_code', sa.Enum('VALIDATION_FAILED', 'ORCHESTRATION_CONFLICT', 'DEPENDENCY_BLOCKED', 'UNKNOWN', name='task_event_error_code_enum'), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_events_created_by_id'), 'task_events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_events_error_code'), 'task_events', ['error_code'], unique=False)
    op.create_index(op.f('ix_task_events_event_lifecycle_state'), 'task_events', ['event_lifecycle_state'], unique=False)
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_occurred_at'), 'task_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_workspace_id'), 'task_events', ['workspace_id'], unique=False)
    op.create_index('ix_task_events_workspace_task_occurred', 'task_events', ['workspace_id', 'task_id', 'occurred_at'], unique=False)
    op.create_table('task_history_records',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('state_from', sa.String(length=64), nullable=True),
    sa.Column('state_to', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('reason_text', sa.String(length=512), nullable=True),
    sa.Column('snapshot_payload', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_history_records_created_by_id'), 'task_history_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_history_records_occurred_at'), 'task_history_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_task_history_records_task_id'), 'task_history_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_records_workspace_id'), 'task_history_records', ['workspace_id'], unique=False)
    op.create_index('ix_task_history_records_workspace_task_created', 'task_history_records', ['workspace_id', 'task_id', 'created_at'], unique=False)
    op.create_index('ix_task_history_records_workspace_task_occurred', 'task_history_records', ['workspace_id', 'task_id', 'occurred_at'], unique=False)
    op.create_table('task_items',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'RELATED', name='task_item_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_items_created_by_id'), 'task_items', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_items_item_id'), 'task_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_task_items_task_id'), 'task_items', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_items_workspace_id'), 'task_items', ['workspace_id'], unique=False)
    op.create_index('ix_task_items_workspace_item', 'task_items', ['workspace_id', 'item_id'], unique=False)
    op.create_index('uix_task_items_active', 'task_items', ['workspace_id', 'task_id', 'item_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_index('uix_task_items_primary_active', 'task_items', ['workspace_id', 'task_id'], unique=True, postgresql_where=sa.text("role = 'PRIMARY' AND removed_at IS NULL"))
    op.create_table('task_notes',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('note_type', sa.Enum('USER_NOTE', 'SYSTEM_NOTE', 'CORRECTION_NOTE', 'RETRACTION_NOTE', name='task_note_type_enum'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_notes_created_by_id'), 'task_notes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_notes_task_id'), 'task_notes', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_notes_workspace_id'), 'task_notes', ['workspace_id'], unique=False)
    op.create_index('ix_task_notes_workspace_task_created', 'task_notes', ['workspace_id', 'task_id', 'created_at'], unique=False)
    op.create_table('task_steps',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'WORKING', 'PAUSED', 'ENDED_SHIFT', 'BLOCKED', 'COMPLETED', 'SKIPPED', 'FAILED', 'CANCELLED', name='task_step_state_enum'), nullable=False),
    sa.Column('readiness_status', sa.Enum('BLOCKED', 'PARTIAL', 'READY', name='task_step_readiness_status_enum'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_worker_id', sa.String(length=64), nullable=True),
    sa.Column('total_dependencies', sa.Integer(), nullable=False),
    sa.Column('completed_dependencies', sa.Integer(), nullable=False),
    sa.Column('recorded_time_marked_wrong', sa.Boolean(), nullable=False),
    sa.Column('taken_from_average', sa.Boolean(), nullable=False),
    sa.Column('working_section_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('assigned_worker_display_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('latest_state_record_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('total_working_seconds', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_seconds', sa.Integer(), nullable=False),
    sa.Column('total_working_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_resolved_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=True),
    sa.CheckConstraint('completed_dependencies <= total_dependencies', name='ck_task_steps_completed_lte_total'),
    sa.CheckConstraint('completed_dependencies >= 0', name='ck_task_steps_completed_deps_positive'),
    sa.CheckConstraint('total_dependencies >= 0', name='ck_task_steps_total_deps_positive'),
    sa.CheckConstraint('total_ended_shift_count >= 0', name='ck_task_steps_ended_shift_count_positive'),
    sa.CheckConstraint('total_ended_shift_seconds >= 0', name='ck_task_steps_ended_shift_seconds_positive'),
    sa.CheckConstraint('total_pause_count >= 0', name='ck_task_steps_pause_count_positive'),
    sa.CheckConstraint('total_pause_seconds >= 0', name='ck_task_steps_pause_seconds_positive'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['latest_state_record_id'], ['step_state_records.client_id'], name='fk_task_steps_latest_state_record_id', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_steps_assigned_worker_id'), 'task_steps', ['assigned_worker_id'], unique=False)
    op.create_index(op.f('ix_task_steps_created_by_id'), 'task_steps', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_task_steps_latest_state_record_id'), 'task_steps', ['latest_state_record_id'], unique=False)
    op.create_index(op.f('ix_task_steps_readiness_status'), 'task_steps', ['readiness_status'], unique=False)
    op.create_index(op.f('ix_task_steps_state'), 'task_steps', ['state'], unique=False)
    op.create_index(op.f('ix_task_steps_task_id'), 'task_steps', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_steps_working_section_id'), 'task_steps', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_task_steps_workspace_id'), 'task_steps', ['workspace_id'], unique=False)
    op.create_index('ix_task_steps_workspace_task_state', 'task_steps', ['workspace_id', 'task_id', 'state'], unique=False)
    op.create_table('item_upholstery_requirements',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('item_upholstery_id', sa.String(length=64), nullable=False),
    sa.Column('upholstery_inventory_id', sa.String(length=64), nullable=True),
    sa.Column('amount_meters', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('value_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Enum('SWEDISH_KRONA', 'DANISH_KRONA', 'EURO', name='item_currency_enum'), nullable=True),
    sa.Column('source', sa.Enum('INVENTORY', 'SURPLUS', name='item_upholstery_requirement_source_enum'), nullable=False),
    sa.Column('state', sa.Enum('AVAILABLE', 'NEEDS_ORDERING', 'ORDERED', 'IN_USE', 'COMPLETED', 'FAILED', name='item_upholstery_requirement_state_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_use_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('amount_meters >= 0', name='ck_item_upholstery_requirements_amount_positive'),
    sa.CheckConstraint('value_minor IS NULL OR value_minor >= 0', name='ck_item_upholstery_requirements_value_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_upholstery_id'], ['item_upholsteries.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_upholstery_requirements_created_by_id'), 'item_upholstery_requirements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_upholstery_requirements_item_upholstery_id'), 'item_upholstery_requirements', ['item_upholstery_id'], unique=False)
    op.create_index(op.f('ix_item_upholstery_requirements_source'), 'item_upholstery_requirements', ['source'], unique=False)
    op.create_index(op.f('ix_item_upholstery_requirements_state'), 'item_upholstery_requirements', ['state'], unique=False)
    op.create_index(op.f('ix_item_upholstery_requirements_workspace_id'), 'item_upholstery_requirements', ['workspace_id'], unique=False)
    op.create_index('ix_item_upholstery_requirements_workspace_upholstery_state', 'item_upholstery_requirements', ['workspace_id', 'item_upholstery_id', 'state'], unique=False)
    op.create_table('step_state_records',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'WORKING', 'PAUSED', 'ENDED_SHIFT', 'BLOCKED', 'COMPLETED', 'SKIPPED', 'FAILED', 'CANCELLED', name='task_step_state_enum'), nullable=False),
    sa.Column('reason', sa.Enum('WAITING_FOR_UPHOLSTERY', 'PAUSE_LUNCH_BREAK', 'PAUSE_COFFEE_BREAK', 'PAUSE_ENDED_SHIFT', 'PAUSE_MEETING', 'PAUSE_OTHER_TASK_PRIORITY', name='step_event_reason_enum'), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('accuracy_measured_by', sa.Enum('USER', 'AI', name='step_state_record_accuracy_measured_by_enum'), nullable=True),
    sa.Column('taken_from_average', sa.Boolean(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('accuracy IS NULL OR (accuracy >= 0 AND accuracy <= 100)', name='ck_step_state_records_accuracy_range'),
    sa.CheckConstraint('exited_at IS NULL OR exited_at >= entered_at', name='ck_step_state_records_exited_after_entered'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['step_id'], ['task_steps.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_step_state_records_created_by_id'), 'step_state_records', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_step_state_records_reason'), 'step_state_records', ['reason'], unique=False)
    op.create_index(op.f('ix_step_state_records_state'), 'step_state_records', ['state'], unique=False)
    op.create_index(op.f('ix_step_state_records_step_id'), 'step_state_records', ['step_id'], unique=False)
    op.create_index(op.f('ix_step_state_records_workspace_id'), 'step_state_records', ['workspace_id'], unique=False)
    op.create_index('ix_step_state_records_workspace_step_entered', 'step_state_records', ['workspace_id', 'step_id', 'entered_at'], unique=False)
    op.create_index('uix_step_state_records_active', 'step_state_records', ['workspace_id', 'step_id'], unique=True, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_table('task_step_assignment_records',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_worker_id', sa.String(length=64), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=64), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('reason_text', sa.String(length=512), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['step_id'], ['task_steps.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_step_assignment_records_assigned_by_id'), 'task_step_assignment_records', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_task_step_assignment_records_assigned_worker_id'), 'task_step_assignment_records', ['assigned_worker_id'], unique=False)
    op.create_index(op.f('ix_task_step_assignment_records_step_id'), 'task_step_assignment_records', ['step_id'], unique=False)
    op.create_index(op.f('ix_task_step_assignment_records_workspace_id'), 'task_step_assignment_records', ['workspace_id'], unique=False)
    op.create_index('ix_task_step_assignment_records_workspace_step_assigned', 'task_step_assignment_records', ['workspace_id', 'step_id', 'assigned_at'], unique=False)
    op.create_index('uix_task_step_assignment_records_active', 'task_step_assignment_records', ['workspace_id', 'step_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('task_step_dependencies',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('dependent_step_id', sa.String(length=64), nullable=False),
    sa.Column('prerequisite_step_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('dependent_step_id != prerequisite_step_id', name='ck_task_step_dependencies_no_self_ref'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dependent_step_id'], ['task_steps.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prerequisite_step_id'], ['task_steps.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_task_step_dependencies_dependent_step_id'), 'task_step_dependencies', ['dependent_step_id'], unique=False)
    op.create_index(op.f('ix_task_step_dependencies_prerequisite_step_id'), 'task_step_dependencies', ['prerequisite_step_id'], unique=False)
    op.create_index(op.f('ix_task_step_dependencies_workspace_id'), 'task_step_dependencies', ['workspace_id'], unique=False)
    op.create_index('uix_task_step_dependencies_active', 'task_step_dependencies', ['workspace_id', 'dependent_step_id', 'prerequisite_step_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_foreign_key('fk_image_last_event_id', 'images', 'image_events', ['last_event_id'], ['client_id'], deferrable=True, use_alter=True)
    op.create_foreign_key('fk_users_last_app_view_record_id', 'users', 'user_app_view_records', ['last_app_view_record_id'], ['client_id'], deferrable=True, use_alter=True)
    op.create_foreign_key('fk_users_last_history_record_id', 'users', 'user_history_records', ['last_history_record_id'], ['client_id'], deferrable=True, use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_last_history_record_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_last_app_view_record_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_image_last_event_id', 'images', type_='foreignkey')
    op.drop_index('uix_task_step_dependencies_active', table_name='task_step_dependencies', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_task_step_dependencies_workspace_id'), table_name='task_step_dependencies')
    op.drop_index(op.f('ix_task_step_dependencies_prerequisite_step_id'), table_name='task_step_dependencies')
    op.drop_index(op.f('ix_task_step_dependencies_dependent_step_id'), table_name='task_step_dependencies')
    op.drop_table('task_step_dependencies')
    op.drop_index('uix_task_step_assignment_records_active', table_name='task_step_assignment_records', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index('ix_task_step_assignment_records_workspace_step_assigned', table_name='task_step_assignment_records')
    op.drop_index(op.f('ix_task_step_assignment_records_workspace_id'), table_name='task_step_assignment_records')
    op.drop_index(op.f('ix_task_step_assignment_records_step_id'), table_name='task_step_assignment_records')
    op.drop_index(op.f('ix_task_step_assignment_records_assigned_worker_id'), table_name='task_step_assignment_records')
    op.drop_index(op.f('ix_task_step_assignment_records_assigned_by_id'), table_name='task_step_assignment_records')
    op.drop_table('task_step_assignment_records')
    op.drop_index('uix_step_state_records_active', table_name='step_state_records', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_index('ix_step_state_records_workspace_step_entered', table_name='step_state_records')
    op.drop_index(op.f('ix_step_state_records_workspace_id'), table_name='step_state_records')
    op.drop_index(op.f('ix_step_state_records_step_id'), table_name='step_state_records')
    op.drop_index(op.f('ix_step_state_records_state'), table_name='step_state_records')
    op.drop_index(op.f('ix_step_state_records_reason'), table_name='step_state_records')
    op.drop_index(op.f('ix_step_state_records_created_by_id'), table_name='step_state_records')
    op.drop_table('step_state_records')
    op.drop_index('ix_item_upholstery_requirements_workspace_upholstery_state', table_name='item_upholstery_requirements')
    op.drop_index(op.f('ix_item_upholstery_requirements_workspace_id'), table_name='item_upholstery_requirements')
    op.drop_index(op.f('ix_item_upholstery_requirements_state'), table_name='item_upholstery_requirements')
    op.drop_index(op.f('ix_item_upholstery_requirements_source'), table_name='item_upholstery_requirements')
    op.drop_index(op.f('ix_item_upholstery_requirements_item_upholstery_id'), table_name='item_upholstery_requirements')
    op.drop_index(op.f('ix_item_upholstery_requirements_created_by_id'), table_name='item_upholstery_requirements')
    op.drop_table('item_upholstery_requirements')
    op.drop_index('ix_task_steps_workspace_task_state', table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_workspace_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_working_section_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_task_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_state'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_readiness_status'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_latest_state_record_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_created_by_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_assigned_worker_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index('ix_task_notes_workspace_task_created', table_name='task_notes')
    op.drop_index(op.f('ix_task_notes_workspace_id'), table_name='task_notes')
    op.drop_index(op.f('ix_task_notes_task_id'), table_name='task_notes')
    op.drop_index(op.f('ix_task_notes_created_by_id'), table_name='task_notes')
    op.drop_table('task_notes')
    op.drop_index('uix_task_items_primary_active', table_name='task_items', postgresql_where=sa.text("role = 'PRIMARY' AND removed_at IS NULL"))
    op.drop_index('uix_task_items_active', table_name='task_items', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index('ix_task_items_workspace_item', table_name='task_items')
    op.drop_index(op.f('ix_task_items_workspace_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_task_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_item_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_created_by_id'), table_name='task_items')
    op.drop_table('task_items')
    op.drop_index('ix_task_history_records_workspace_task_occurred', table_name='task_history_records')
    op.drop_index('ix_task_history_records_workspace_task_created', table_name='task_history_records')
    op.drop_index(op.f('ix_task_history_records_workspace_id'), table_name='task_history_records')
    op.drop_index(op.f('ix_task_history_records_task_id'), table_name='task_history_records')
    op.drop_index(op.f('ix_task_history_records_occurred_at'), table_name='task_history_records')
    op.drop_index(op.f('ix_task_history_records_created_by_id'), table_name='task_history_records')
    op.drop_table('task_history_records')
    op.drop_index('ix_task_events_workspace_task_occurred', table_name='task_events')
    op.drop_index(op.f('ix_task_events_workspace_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_occurred_at'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_lifecycle_state'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_error_code'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_created_by_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('ix_item_upholsteries_workspace_item', table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_workspace_id'), table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_upholstery_id'), table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_source'), table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_item_id'), table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_created_by_id'), table_name='item_upholsteries')
    op.drop_index(op.f('ix_item_upholsteries_active_requirement_id'), table_name='item_upholsteries')
    op.drop_table('item_upholsteries')
    op.drop_index('ix_item_issues_workspace_state', table_name='item_issues')
    op.drop_index('ix_item_issues_workspace_item_state', table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_workspace_id'), table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_state'), table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_item_id'), table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_issue_type_id'), table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_issue_severity_id'), table_name='item_issues')
    op.drop_index(op.f('ix_item_issues_created_by_id'), table_name='item_issues')
    op.drop_table('item_issues')
    op.drop_index(op.f('ix_working_section_supported_issue_types_workspace_id'), table_name='working_section_supported_issue_types')
    op.drop_index(op.f('ix_working_section_supported_issue_types_working_section_id'), table_name='working_section_supported_issue_types')
    op.drop_index(op.f('ix_working_section_supported_issue_types_issue_type_id'), table_name='working_section_supported_issue_types')
    op.drop_table('working_section_supported_issue_types')
    op.drop_index('uix_working_section_memberships_active', table_name='working_section_memberships', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_working_section_memberships_workspace_id'), table_name='working_section_memberships')
    op.drop_index(op.f('ix_working_section_memberships_working_section_id'), table_name='working_section_memberships')
    op.drop_index('ix_working_section_memberships_user_removed', table_name='working_section_memberships')
    op.drop_index(op.f('ix_working_section_memberships_user_id'), table_name='working_section_memberships')
    op.drop_index('ix_working_section_memberships_section_removed', table_name='working_section_memberships')
    op.drop_table('working_section_memberships')
    op.drop_index(op.f('ix_working_section_item_categories_workspace_id'), table_name='working_section_item_categories')
    op.drop_index(op.f('ix_working_section_item_categories_working_section_id'), table_name='working_section_item_categories')
    op.drop_index(op.f('ix_working_section_item_categories_item_category_id'), table_name='working_section_item_categories')
    op.drop_table('working_section_item_categories')
    op.drop_index(op.f('ix_working_section_dependencies_workspace_id'), table_name='working_section_dependencies')
    op.drop_index(op.f('ix_working_section_dependencies_prerequisite_section_id'), table_name='working_section_dependencies')
    op.drop_index(op.f('ix_working_section_dependencies_dependent_section_id'), table_name='working_section_dependencies')
    op.drop_table('working_section_dependencies')
    op.drop_index(op.f('ix_upholstery_inventory_threshold_policies_workspace_id'), table_name='upholstery_inventory_threshold_policies')
    op.drop_index(op.f('ix_upholstery_inventory_threshold_policies_upholstery_id'), table_name='upholstery_inventory_threshold_policies')
    op.drop_index(op.f('ix_upholstery_inventory_threshold_policies_scope'), table_name='upholstery_inventory_threshold_policies')
    op.drop_index(op.f('ix_upholstery_inventory_threshold_policies_created_by_id'), table_name='upholstery_inventory_threshold_policies')
    op.drop_table('upholstery_inventory_threshold_policies')
    op.drop_index(op.f('ix_upholstery_inventory_workspace_id'), table_name='upholstery_inventory')
    op.drop_index(op.f('ix_upholstery_inventory_upholstery_id'), table_name='upholstery_inventory')
    op.drop_index(op.f('ix_upholstery_inventory_inventory_condition'), table_name='upholstery_inventory')
    op.drop_index(op.f('ix_upholstery_inventory_created_by_id'), table_name='upholstery_inventory')
    op.drop_table('upholstery_inventory')
    op.drop_index('ix_tasks_workspace_state_scheduled_start', table_name='tasks')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_state'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_latest_history_record_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_latest_event_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('uix_items_workspace_sku', table_name='items', postgresql_where=sa.text('sku IS NOT NULL'))
    op.drop_index('uix_items_workspace_article_number', table_name='items', postgresql_where=sa.text('article_number IS NOT NULL'))
    op.drop_index('ix_items_workspace_state', table_name='items')
    op.drop_index(op.f('ix_items_workspace_id'), table_name='items')
    op.drop_index(op.f('ix_items_state'), table_name='items')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_item_category_id'), table_name='items')
    op.drop_index(op.f('ix_items_created_by_id'), table_name='items')
    op.drop_index(op.f('ix_items_article_number'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_issue_category_configs_workspace_id'), table_name='issue_category_configs')
    op.drop_index(op.f('ix_issue_category_configs_item_category_id'), table_name='issue_category_configs')
    op.drop_index(op.f('ix_issue_category_configs_issue_type_id'), table_name='issue_category_configs')
    op.drop_index(op.f('ix_issue_category_configs_created_by_id'), table_name='issue_category_configs')
    op.drop_table('issue_category_configs')
    op.drop_index(op.f('ix_customer_history_records_workspace_id'), table_name='customer_history_records')
    op.drop_index('ix_customer_history_records_workspace_customer_occurred', table_name='customer_history_records')
    op.drop_index('ix_customer_history_records_workspace_customer_created', table_name='customer_history_records')
    op.drop_index(op.f('ix_customer_history_records_occurred_at'), table_name='customer_history_records')
    op.drop_index(op.f('ix_customer_history_records_customer_id'), table_name='customer_history_records')
    op.drop_index(op.f('ix_customer_history_records_created_by_id'), table_name='customer_history_records')
    op.drop_index(op.f('ix_customer_history_records_change_type'), table_name='customer_history_records')
    op.drop_table('customer_history_records')
    op.drop_index(op.f('ix_working_sections_workspace_id'), table_name='working_sections')
    op.drop_index(op.f('ix_working_sections_created_by_id'), table_name='working_sections')
    op.drop_table('working_sections')
    op.drop_index('ix_user_work_profiles_workspace_user', table_name='user_work_profiles')
    op.drop_index(op.f('ix_user_work_profiles_workspace_id'), table_name='user_work_profiles')
    op.drop_index(op.f('ix_user_work_profiles_user_id'), table_name='user_work_profiles')
    op.drop_index(op.f('ix_user_work_profiles_created_by_id'), table_name='user_work_profiles')
    op.drop_table('user_work_profiles')
    op.drop_index('uix_user_shift_state_records_active', table_name='user_shift_state_records', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_index(op.f('ix_user_shift_state_records_workspace_id'), table_name='user_shift_state_records')
    op.drop_index('ix_user_shift_state_records_user_workspace_exited', table_name='user_shift_state_records')
    op.drop_index('ix_user_shift_state_records_user_workspace_entered', table_name='user_shift_state_records')
    op.drop_index(op.f('ix_user_shift_state_records_user_id'), table_name='user_shift_state_records')
    op.drop_table('user_shift_state_records')
    op.drop_index('uix_upholsteries_workspace_code', table_name='upholsteries', postgresql_where=sa.text('code IS NOT NULL'))
    op.drop_index(op.f('ix_upholsteries_workspace_id'), table_name='upholsteries')
    op.drop_index(op.f('ix_upholsteries_created_by_id'), table_name='upholsteries')
    op.drop_table('upholsteries')
    op.drop_index(op.f('ix_static_costs_workspace_id'), table_name='static_costs')
    op.drop_index(op.f('ix_static_costs_created_by_id'), table_name='static_costs')
    op.drop_table('static_costs')
    op.drop_index('ix_item_categories_workspace_major_category', table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_workspace_id'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_major_category'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_created_by_id'), table_name='item_categories')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_issue_types_workspace_id'), table_name='issue_types')
    op.drop_index(op.f('ix_issue_types_source'), table_name='issue_types')
    op.drop_index(op.f('ix_issue_types_created_by_id'), table_name='issue_types')
    op.drop_table('issue_types')
    op.drop_index(op.f('ix_issue_severities_workspace_id'), table_name='issue_severities')
    op.drop_index(op.f('ix_issue_severities_created_by_id'), table_name='issue_severities')
    op.drop_table('issue_severities')
    op.drop_index('ix_customers_workspace_phone_normalized', table_name='customers')
    op.drop_index('ix_customers_workspace_phone', table_name='customers')
    op.drop_index(op.f('ix_customers_workspace_id'), table_name='customers')
    op.drop_index('ix_customers_workspace_email_normalized', table_name='customers')
    op.drop_index('ix_customers_workspace_email', table_name='customers')
    op.drop_index('ix_customers_workspace_display_name', table_name='customers')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_primary_phone_number_normalized'), table_name='customers')
    op.drop_index(op.f('ix_customers_primary_email_normalized'), table_name='customers')
    op.drop_index(op.f('ix_customers_latest_history_record_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_by_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
