"""item_economics_schema

Revision ID: 90cdd23a828e
Revises: 7758ea23764e
Create Date: 2026-08-12 12:43:01.094308
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '90cdd23a828e'
down_revision: Union[str, None] = '7758ea23764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_cost_model_term_calculation_type_enum = postgresql.ENUM(
    "percentage_of_expected_sale_price", "fixed_amount", "item_purchase_cost",
    name="cost_model_term_calculation_type_enum", create_type=False,
)
_item_cost_evaluation_kind_enum = postgresql.ENUM(
    "projection", "committed", name="item_cost_evaluation_kind_enum", create_type=False,
)
_production_cost_basis_version_currency_enum = postgresql.ENUM(
    "swedish_krona", "danish_krona", "euro",
    name="production_cost_basis_version_currency_enum", create_type=False,
)
_cost_model_version_currency_enum = postgresql.ENUM(
    "swedish_krona", "danish_krona", "euro",
    name="cost_model_version_currency_enum", create_type=False,
)
_item_valuation_currency_enum = postgresql.ENUM(
    "swedish_krona", "danish_krona", "euro",
    name="item_valuation_currency_enum", create_type=False,
)
_business_task_type_enum = postgresql.ENUM(
    "return", "pre_order", "internal", name="business_task_type_enum", create_type=False,
)
_task_return_source_enum = postgresql.ENUM(
    "after_purchase", "before_purchase", "store_return", name="task_return_source_enum", create_type=False,
)
_task_state_enum = postgresql.ENUM(
    "pending", "assigned", "working", "stalled", "ready", "resolved", "failed", "cancelled",
    name="task_state_enum", create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _cost_model_term_calculation_type_enum.create(op.get_bind(), checkfirst=True)
    _item_cost_evaluation_kind_enum.create(op.get_bind(), checkfirst=True)
    _production_cost_basis_version_currency_enum.create(op.get_bind(), checkfirst=True)
    _cost_model_version_currency_enum.create(op.get_bind(), checkfirst=True)
    _item_valuation_currency_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('cost_model_versions',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('currency', _cost_model_version_currency_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_cost_model_versions_effective_window'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_cost_model_versions_created_by_id'), 'cost_model_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cost_model_versions_workspace_id'), 'cost_model_versions', ['workspace_id'], unique=False)
    op.create_index('uix_cost_model_versions_open', 'cost_model_versions', ['workspace_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL AND is_deleted = false'))
    op.create_table('production_cost_groups',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_production_cost_groups_created_by_id'), 'production_cost_groups', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_production_cost_groups_workspace_id'), 'production_cost_groups', ['workspace_id'], unique=False)
    op.create_index('uix_production_cost_groups_name_active', 'production_cost_groups', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('cost_model_terms',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('cost_model_version_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calculation_type', _cost_model_term_calculation_type_enum, nullable=False),
    sa.Column('percent_value', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_amount_minor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("(calculation_type = 'percentage_of_expected_sale_price' AND percent_value IS NOT NULL AND fixed_amount_minor IS NULL) OR (calculation_type = 'fixed_amount' AND percent_value IS NULL AND fixed_amount_minor IS NOT NULL) OR (calculation_type = 'item_purchase_cost' AND percent_value IS NULL AND fixed_amount_minor IS NULL)", name='ck_cost_model_terms_value_by_type'),
    sa.CheckConstraint('fixed_amount_minor IS NULL OR fixed_amount_minor >= 0', name='ck_cost_model_terms_fixed_amount_minor_non_negative'),
    sa.CheckConstraint('percent_value IS NULL OR percent_value >= 0', name='ck_cost_model_terms_percent_value_non_negative'),
    sa.ForeignKeyConstraint(['cost_model_version_id'], ['cost_model_versions.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_cost_model_terms_cost_model_version_id'), 'cost_model_terms', ['cost_model_version_id'], unique=False)
    op.create_index(op.f('ix_cost_model_terms_created_by_id'), 'cost_model_terms', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cost_model_terms_workspace_id'), 'cost_model_terms', ['workspace_id'], unique=False)
    op.create_index('uix_cost_model_terms_name_active', 'cost_model_terms', ['cost_model_version_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uix_cost_model_terms_purchase_cost', 'cost_model_terms', ['cost_model_version_id'], unique=True, postgresql_where=sa.text("calculation_type = 'item_purchase_cost' AND is_deleted = false"))
    op.create_table('production_cost_basis_versions',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('production_cost_group_id', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('fixed_monthly_cost_minor', sa.Integer(), nullable=False),
    sa.Column('currency', _production_cost_basis_version_currency_enum, nullable=False),
    sa.Column('monthly_paid_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('planning_utilization_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_per_worker_minute_minor', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('cost_per_worker_minute_minor > 0', name='ck_pcbv_cost_per_worker_minute_minor_positive'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_production_cost_basis_versions_effective_window'),
    sa.CheckConstraint('fixed_monthly_cost_minor > 0', name='ck_pcbv_fixed_monthly_cost_minor_positive'),
    sa.CheckConstraint('monthly_paid_hours > 0', name='ck_pcbv_monthly_paid_hours_positive'),
    sa.CheckConstraint('planning_utilization_percent <= 100', name='ck_pcbv_planning_utilization_percent_max'),
    sa.CheckConstraint('planning_utilization_percent > 0', name='ck_pcbv_planning_utilization_percent_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_cost_group_id'], ['production_cost_groups.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_production_cost_basis_versions_created_by_id'), 'production_cost_basis_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_production_cost_basis_versions_production_cost_group_id'), 'production_cost_basis_versions', ['production_cost_group_id'], unique=False)
    op.create_index(op.f('ix_production_cost_basis_versions_workspace_id'), 'production_cost_basis_versions', ['workspace_id'], unique=False)
    op.create_index('uix_production_cost_basis_versions_open', 'production_cost_basis_versions', ['production_cost_group_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL AND is_deleted = false'))
    op.create_table('production_cost_group_sections',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('production_cost_group_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_id', sa.String(length=64), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_cost_group_id'], ['production_cost_groups.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['removed_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_production_cost_group_sections_added_by_id'), 'production_cost_group_sections', ['added_by_id'], unique=False)
    op.create_index(op.f('ix_production_cost_group_sections_production_cost_group_id'), 'production_cost_group_sections', ['production_cost_group_id'], unique=False)
    op.create_index(op.f('ix_production_cost_group_sections_working_section_id'), 'production_cost_group_sections', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_production_cost_group_sections_workspace_id'), 'production_cost_group_sections', ['workspace_id'], unique=False)
    op.create_index('uix_production_cost_group_sections_active', 'production_cost_group_sections', ['workspace_id', 'working_section_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('item_cost_evaluations',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('kind', _item_cost_evaluation_kind_enum, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('task_type_snapshot', _business_task_type_enum, nullable=False),
    sa.Column('return_source_snapshot', _task_return_source_enum, nullable=True),
    sa.Column('expected_sale_price_minor', sa.Integer(), nullable=False),
    sa.Column('purchase_cost_minor', sa.Integer(), nullable=True),
    sa.Column('currency', _item_valuation_currency_enum, nullable=False),
    sa.Column('cost_model_version_id', sa.String(length=64), nullable=False),
    sa.Column('production_cost_group_id', sa.String(length=64), nullable=False),
    sa.Column('production_cost_basis_version_id', sa.String(length=64), nullable=False),
    sa.Column('monthly_paid_hours_snapshot', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('planning_utilization_percent_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_monthly_cost_minor_snapshot', sa.Integer(), nullable=False),
    sa.Column('cost_per_worker_minute_minor_snapshot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('production_budget_minor', sa.Integer(), nullable=False),
    sa.Column('allowed_worker_minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=64), nullable=True),
    sa.Column('promoted_from_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('expected_sale_price_minor >= 0', name='ck_ice_expected_sale_price_minor_non_negative'),
    sa.CheckConstraint('purchase_cost_minor IS NULL OR purchase_cost_minor >= 0', name='ck_ice_purchase_cost_minor_non_negative'),
    sa.ForeignKeyConstraint(['cost_model_version_id'], ['cost_model_versions.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_cost_basis_version_id'], ['production_cost_basis_versions.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_cost_group_id'], ['production_cost_groups.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_cost_evaluations_cost_model_version_id'), 'item_cost_evaluations', ['cost_model_version_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_created_by_id'), 'item_cost_evaluations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_item_id'), 'item_cost_evaluations', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_production_cost_basis_version_id'), 'item_cost_evaluations', ['production_cost_basis_version_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_production_cost_group_id'), 'item_cost_evaluations', ['production_cost_group_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_promoted_from_id'), 'item_cost_evaluations', ['promoted_from_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_superseded_by_id'), 'item_cost_evaluations', ['superseded_by_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_task_id'), 'item_cost_evaluations', ['task_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluations_workspace_id'), 'item_cost_evaluations', ['workspace_id'], unique=False)
    op.create_index('uix_item_cost_evaluations_current', 'item_cost_evaluations', ['task_id'], unique=True, postgresql_where=sa.text("kind = 'committed' AND superseded_at IS NULL AND is_deleted = false"))
    op.create_table('item_valuations',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('expected_sale_price_minor', sa.Integer(), nullable=True),
    sa.Column('purchase_cost_minor', sa.Integer(), nullable=True),
    sa.Column('currency', _item_valuation_currency_enum, nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('expected_sale_price_minor IS NOT NULL OR purchase_cost_minor IS NOT NULL', name='ck_item_valuations_amount_present'),
    sa.CheckConstraint('expected_sale_price_minor IS NULL OR expected_sale_price_minor >= 0', name='ck_item_valuations_expected_sale_price_minor_non_negative'),
    sa.CheckConstraint('purchase_cost_minor IS NULL OR purchase_cost_minor >= 0', name='ck_item_valuations_purchase_cost_minor_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_valuations_created_by_id'), 'item_valuations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_item_valuations_item_id'), 'item_valuations', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_valuations_superseded_by_id'), 'item_valuations', ['superseded_by_id'], unique=False)
    op.create_index(op.f('ix_item_valuations_workspace_id'), 'item_valuations', ['workspace_id'], unique=False)
    op.create_index('uix_item_valuations_current', 'item_valuations', ['item_id'], unique=True, postgresql_where=sa.text('superseded_at IS NULL AND is_deleted = false'))
    op.create_table('item_cost_evaluation_terms',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('evaluation_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calculation_type', _cost_model_term_calculation_type_enum, nullable=False),
    sa.Column('percent_value', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fixed_amount_minor', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['item_cost_evaluations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_item_cost_evaluation_terms_evaluation_id'), 'item_cost_evaluation_terms', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_item_cost_evaluation_terms_workspace_id'), 'item_cost_evaluation_terms', ['workspace_id'], unique=False)
    op.create_table('item_cost_results',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('evaluation_id', sa.String(length=64), nullable=False),
    sa.Column('actual_worker_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_worker_minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('consumed_cost_minor', sa.Integer(), nullable=False),
    sa.Column('variance_worker_minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variance_cost_minor', sa.Integer(), nullable=False),
    sa.Column('task_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_state_snapshot', _task_state_enum, nullable=False),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint('actual_worker_seconds >= 0', name='ck_item_cost_results_actual_worker_seconds_non_negative'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['item_cost_evaluations.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('task_id', name='uq_item_cost_results_task_id')
    )
    op.create_index(op.f('ix_item_cost_results_evaluation_id'), 'item_cost_results', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_item_cost_results_item_id'), 'item_cost_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_cost_results_task_id'), 'item_cost_results', ['task_id'], unique=False)
    op.create_index(op.f('ix_item_cost_results_workspace_id'), 'item_cost_results', ['workspace_id'], unique=False)
    op.create_foreign_key(
        "fk_item_cost_evaluations_superseded_by_id", "item_cost_evaluations", "item_cost_evaluations",
        ["superseded_by_id"], ["client_id"], ondelete="RESTRICT", use_alter=True,
    )
    op.create_foreign_key(
        "fk_item_cost_evaluations_promoted_from_id", "item_cost_evaluations", "item_cost_evaluations",
        ["promoted_from_id"], ["client_id"], ondelete="RESTRICT", use_alter=True,
    )
    op.create_foreign_key(
        "fk_item_valuations_superseded_by_id", "item_valuations", "item_valuations",
        ["superseded_by_id"], ["client_id"], ondelete="RESTRICT", use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_item_valuations_superseded_by_id", "item_valuations", type_="foreignkey")
    op.drop_index(op.f('ix_item_cost_results_workspace_id'), table_name='item_cost_results')
    op.drop_index(op.f('ix_item_cost_results_task_id'), table_name='item_cost_results')
    op.drop_index(op.f('ix_item_cost_results_item_id'), table_name='item_cost_results')
    op.drop_index(op.f('ix_item_cost_results_evaluation_id'), table_name='item_cost_results')
    op.drop_table('item_cost_results')
    op.drop_index(op.f('ix_item_cost_evaluation_terms_workspace_id'), table_name='item_cost_evaluation_terms')
    op.drop_index(op.f('ix_item_cost_evaluation_terms_evaluation_id'), table_name='item_cost_evaluation_terms')
    op.drop_table('item_cost_evaluation_terms')
    op.drop_index('uix_item_valuations_current', table_name='item_valuations', postgresql_where=sa.text('superseded_at IS NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_item_valuations_workspace_id'), table_name='item_valuations')
    op.drop_index(op.f('ix_item_valuations_superseded_by_id'), table_name='item_valuations')
    op.drop_index(op.f('ix_item_valuations_item_id'), table_name='item_valuations')
    op.drop_index(op.f('ix_item_valuations_created_by_id'), table_name='item_valuations')
    op.drop_table('item_valuations')
    op.drop_constraint("fk_item_cost_evaluations_promoted_from_id", "item_cost_evaluations", type_="foreignkey")
    op.drop_constraint("fk_item_cost_evaluations_superseded_by_id", "item_cost_evaluations", type_="foreignkey")
    op.drop_index('uix_item_cost_evaluations_current', table_name='item_cost_evaluations', postgresql_where=sa.text("kind = 'committed' AND superseded_at IS NULL AND is_deleted = false"))
    op.drop_index(op.f('ix_item_cost_evaluations_workspace_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_task_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_superseded_by_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_promoted_from_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_production_cost_group_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_production_cost_basis_version_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_item_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_created_by_id'), table_name='item_cost_evaluations')
    op.drop_index(op.f('ix_item_cost_evaluations_cost_model_version_id'), table_name='item_cost_evaluations')
    op.drop_table('item_cost_evaluations')
    op.drop_index('uix_production_cost_group_sections_active', table_name='production_cost_group_sections', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_production_cost_group_sections_workspace_id'), table_name='production_cost_group_sections')
    op.drop_index(op.f('ix_production_cost_group_sections_working_section_id'), table_name='production_cost_group_sections')
    op.drop_index(op.f('ix_production_cost_group_sections_production_cost_group_id'), table_name='production_cost_group_sections')
    op.drop_index(op.f('ix_production_cost_group_sections_added_by_id'), table_name='production_cost_group_sections')
    op.drop_table('production_cost_group_sections')
    op.drop_index('uix_production_cost_basis_versions_open', table_name='production_cost_basis_versions', postgresql_where=sa.text('effective_to IS NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_production_cost_basis_versions_workspace_id'), table_name='production_cost_basis_versions')
    op.drop_index(op.f('ix_production_cost_basis_versions_production_cost_group_id'), table_name='production_cost_basis_versions')
    op.drop_index(op.f('ix_production_cost_basis_versions_created_by_id'), table_name='production_cost_basis_versions')
    op.drop_table('production_cost_basis_versions')
    op.drop_index('uix_cost_model_terms_purchase_cost', table_name='cost_model_terms', postgresql_where=sa.text("calculation_type = 'item_purchase_cost' AND is_deleted = false"))
    op.drop_index('uix_cost_model_terms_name_active', table_name='cost_model_terms', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_cost_model_terms_workspace_id'), table_name='cost_model_terms')
    op.drop_index(op.f('ix_cost_model_terms_created_by_id'), table_name='cost_model_terms')
    op.drop_index(op.f('ix_cost_model_terms_cost_model_version_id'), table_name='cost_model_terms')
    op.drop_table('cost_model_terms')
    op.drop_index('uix_production_cost_groups_name_active', table_name='production_cost_groups', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_production_cost_groups_workspace_id'), table_name='production_cost_groups')
    op.drop_index(op.f('ix_production_cost_groups_created_by_id'), table_name='production_cost_groups')
    op.drop_table('production_cost_groups')
    op.drop_index('uix_cost_model_versions_open', table_name='cost_model_versions', postgresql_where=sa.text('effective_to IS NULL AND is_deleted = false'))
    op.drop_index(op.f('ix_cost_model_versions_workspace_id'), table_name='cost_model_versions')
    op.drop_index(op.f('ix_cost_model_versions_created_by_id'), table_name='cost_model_versions')
    op.drop_table('cost_model_versions')
    _item_valuation_currency_enum.drop(op.get_bind(), checkfirst=True)
    _cost_model_version_currency_enum.drop(op.get_bind(), checkfirst=True)
    _production_cost_basis_version_currency_enum.drop(op.get_bind(), checkfirst=True)
    _item_cost_evaluation_kind_enum.drop(op.get_bind(), checkfirst=True)
    _cost_model_term_calculation_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
