"""backfill_other_task_priority_transition_reason

One-time data backfill (system_transition_reasons phase 3, T5): historical rows whose
`pause_reason_id` (or, on the derived table, `reason`) points at the catalog row with
slug `pause_other_task_priority` are retyped to `transition_reason =
'other_task_priority'` and their catalog reference nulled. After it, the system
representation of a task-switch auto-pause is the same on historical rows as on rows
the cutover writes, and the catalog row is unreferenced.

**Selection is by the `pause_other_task_priority` slug alone** — never by
`is_system_managed`, never by a set of "system" rows. Rows pointing at
`pause_ended_shift` (a worker's pick and a clock-out write are historically
indistinguishable) and at `pause_case_created` (worker-chosen, resolves through its
soft-deleted anchor) are deliberately untouched, and the migration asserts their
counts unchanged. `user_declared_state_records` is not touched by any statement here.

**Reversibility.** Post-cutover writers produce rows byte-identical in shape to the
backfilled ones (`transition_reason` set, catalog reference NULL), so no predicate can
distinguish "backfilled" from "organically written" after the fact. The migration
therefore journals exactly which rows it rewrote — `transition_reason_backfill_journal`
(table_name, client_id, previous reference) — and `downgrade` restores precisely those
rows and drops the journal. The journal is dropped by the retirement phase once the
backfill is verified in production; until then it is the only record that makes this
migration reversible.

**Idempotent by predicate.** Every UPDATE selects rows that still carry the catalog
reference with `transition_reason IS NULL`; a migrated row matches neither, so
re-executing the statements affects zero rows.

Hand-written rather than autogenerated on purpose: this is a data migration, and
autogenerate would also sweep in pre-existing schema drift owned by the
declared-worker-states baseline (see a7d21f4c8b03's docstring).

Revision ID: 97b60e06d42a
Revises: a7d21f4c8b03
Create Date: 2026-07-31 19:49:09.369606
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '97b60e06d42a'
down_revision: Union[str, None] = 'a7d21f4c8b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SLUG = 'pause_other_task_priority'
_TRANSITION = 'other_task_priority'
_JOURNAL = 'transition_reason_backfill_journal'

# The two untouched populations, asserted unchanged (not merely left alone).
_GUARDED_SLUGS = ('pause_ended_shift', 'pause_case_created')

_GUARDED_COUNTS_SQL = sa.text(
    """
    SELECT
        (SELECT count(*) FROM step_state_records ssr
         JOIN pause_reasons pr ON pr.client_id = ssr.pause_reason_id
         WHERE pr.slug = :ended_shift),
        (SELECT count(*) FROM step_state_records ssr
         JOIN pause_reasons pr ON pr.client_id = ssr.pause_reason_id
         WHERE pr.slug = :case_created),
        (SELECT count(*) FROM user_shift_state_records uss
         JOIN pause_reasons pr ON pr.client_id = uss.reason
         WHERE pr.slug IN (:ended_shift, :case_created)),
        (SELECT count(*) FROM user_declared_state_records)
    """
)


def _guarded_counts(bind) -> tuple:
    return tuple(
        bind.execute(
            _GUARDED_COUNTS_SQL,
            {"ended_shift": _GUARDED_SLUGS[0], "case_created": _GUARDED_SLUGS[1]},
        ).one()
    )


def upgrade() -> None:
    bind = op.get_bind()

    # A row carrying BOTH the catalog reference and a transition_reason would be
    # contradictory (no writer has ever produced one); rewriting it would destroy
    # whichever half is the true record. Refuse rather than guess.
    conflicted = bind.execute(
        sa.text(
            """
            SELECT
                (SELECT count(*) FROM step_state_records ssr
                 JOIN pause_reasons pr ON pr.client_id = ssr.pause_reason_id
                 WHERE pr.slug = :slug AND ssr.transition_reason IS NOT NULL)
                +
                (SELECT count(*) FROM user_shift_state_records uss
                 JOIN pause_reasons pr ON pr.client_id = uss.reason
                 WHERE pr.slug = :slug AND uss.transition_reason IS NOT NULL)
            """
        ),
        {"slug": _SLUG},
    ).scalar_one()
    if conflicted:
        raise RuntimeError(
            f"transition_reason backfill refused: {conflicted} rows reference "
            f"'{_SLUG}' while already carrying a transition_reason — investigate "
            "before migrating; rewriting them would destroy real history"
        )

    guarded_before = _guarded_counts(bind)

    op.execute(
        sa.text(
            f"""
            CREATE TABLE IF NOT EXISTS {_JOURNAL} (
                table_name  varchar(64) NOT NULL,
                client_id   varchar(64) NOT NULL,
                previous_pause_reason_id varchar(64) NOT NULL,
                PRIMARY KEY (table_name, client_id)
            )
            """
        )
    )

    bind.execute(
        sa.text(
            f"""
            INSERT INTO {_JOURNAL} (table_name, client_id, previous_pause_reason_id)
            SELECT 'step_state_records', ssr.client_id, ssr.pause_reason_id
            FROM step_state_records ssr
            JOIN pause_reasons pr ON pr.client_id = ssr.pause_reason_id
            WHERE pr.slug = :slug AND ssr.transition_reason IS NULL
            ON CONFLICT (table_name, client_id) DO NOTHING
            """
        ),
        {"slug": _SLUG},
    )
    bind.execute(
        sa.text(
            f"""
            INSERT INTO {_JOURNAL} (table_name, client_id, previous_pause_reason_id)
            SELECT 'user_shift_state_records', uss.client_id, uss.reason
            FROM user_shift_state_records uss
            JOIN pause_reasons pr ON pr.client_id = uss.reason
            WHERE pr.slug = :slug AND uss.transition_reason IS NULL
            ON CONFLICT (table_name, client_id) DO NOTHING
            """
        ),
        {"slug": _SLUG},
    )

    bind.execute(
        sa.text(
            """
            UPDATE step_state_records AS ssr
            SET transition_reason = :transition, pause_reason_id = NULL
            FROM pause_reasons AS pr
            WHERE pr.client_id = ssr.pause_reason_id
              AND pr.slug = :slug
              AND ssr.transition_reason IS NULL
            """
        ),
        {"slug": _SLUG, "transition": _TRANSITION},
    )
    bind.execute(
        sa.text(
            """
            UPDATE user_shift_state_records AS uss
            SET transition_reason = :transition, reason = NULL
            FROM pause_reasons AS pr
            WHERE pr.client_id = uss.reason
              AND pr.slug = :slug
              AND uss.transition_reason IS NULL
            """
        ),
        {"slug": _SLUG, "transition": _TRANSITION},
    )

    remaining = bind.execute(
        sa.text(
            """
            SELECT
                (SELECT count(*) FROM step_state_records ssr
                 JOIN pause_reasons pr ON pr.client_id = ssr.pause_reason_id
                 WHERE pr.slug = :slug)
                +
                (SELECT count(*) FROM user_shift_state_records uss
                 JOIN pause_reasons pr ON pr.client_id = uss.reason
                 WHERE pr.slug = :slug)
            """
        ),
        {"slug": _SLUG},
    ).scalar_one()
    if remaining:
        raise RuntimeError(
            f"transition_reason backfill incomplete: {remaining} rows still "
            f"reference '{_SLUG}'"
        )

    guarded_after = _guarded_counts(bind)
    if guarded_before != guarded_after:
        raise RuntimeError(
            "transition_reason backfill touched a guarded population: "
            f"(ended_shift steps, case_created steps, derived refs, declared rows) "
            f"went {guarded_before} -> {guarded_after}"
        )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            f"""
            UPDATE step_state_records AS ssr
            SET pause_reason_id = j.previous_pause_reason_id, transition_reason = NULL
            FROM {_JOURNAL} AS j
            WHERE j.table_name = 'step_state_records'
              AND j.client_id = ssr.client_id
            """
        )
    )
    bind.execute(
        sa.text(
            f"""
            UPDATE user_shift_state_records AS uss
            SET reason = j.previous_pause_reason_id, transition_reason = NULL
            FROM {_JOURNAL} AS j
            WHERE j.table_name = 'user_shift_state_records'
              AND j.client_id = uss.client_id
            """
        )
    )
    op.execute(f"DROP TABLE IF EXISTS {_JOURNAL}")
