"""initial_schema

Revision ID: a1312183fdfb
Revises: 
Create Date: 2026-05-15 10:56:09.037708
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a1312183fdfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_types',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('entity_type', sa.Enum('TASK', 'CUSTOMER', name='case_link_entity_type_enum'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_case_types_entity_type'), 'case_types', ['entity_type'], unique=False)
    op.create_table('content_mentions',
    sa.Column('mention_table', sa.String(length=128), nullable=False),
    sa.Column('mention_id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('mention_table', 'mention_id', name='uq_content_mention')
    )
    op.create_index(op.f('ix_content_mentions_mention_id'), 'content_mentions', ['mention_id'], unique=False)
    op.create_index(op.f('ix_content_mentions_mention_table'), 'content_mentions', ['mention_table'], unique=False)
    op.create_table('delayed_schedulers',
    sa.Column('type', sa.Enum('NOTIFY_TO_CUSTOMER', 'SEND_REPORT', 'REMINDER', 'BATCH_NOTIFICATION', name='delayed_scheduler_type_enum'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'FIRED', 'PAUSED', 'CANCELED', 'ERROR', name='scheduler_state_enum'), nullable=False),
    sa.Column('origin_source', sa.Enum('COMMAND', 'WORKER', name='scheduler_origin_source_enum'), nullable=False),
    sa.Column('origin_id', sa.String(length=64), nullable=True),
    sa.Column('event_client_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_delayed_schedulers_event_client_id'), 'delayed_schedulers', ['event_client_id'], unique=False)
    op.create_index(op.f('ix_delayed_schedulers_scheduled_for'), 'delayed_schedulers', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_delayed_schedulers_state'), 'delayed_schedulers', ['state'], unique=False)
    op.create_table('execution_tasks',
    sa.Column('task_type', sa.Enum('NOTIFICATION', 'UPLOAD_IMAGE', 'DELIVER_WEBHOOK', 'CREATE_NOTIFICATIONS', 'SEND_PUSH_NOTIFICATION', 'DELAYED_NOTIFY_TO_CUSTOMER', 'DELAYED_SEND_REPORT', 'DELAYED_REMINDER', 'DELAYED_BATCH_NOTIFICATION', 'RECURRING_SEND_REPORT', 'RECURRING_REMINDER', 'RECURRING_PIN_TASK', 'RECORD_VIEW_START', 'RECORD_VIEW_END', name='task_type_enum'), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'PENDING', 'IN_PROGRESS', 'RETRYING', 'RETRY_SCHEDULED', 'COMPLETED', 'FAIL', 'CANCEL', name='execution_task_state_enum'), nullable=False),
    sa.Column('try_count', sa.Integer(), nullable=False),
    sa.Column('max_try', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_execution_tasks_next_retry_at'), 'execution_tasks', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_execution_tasks_state'), 'execution_tasks', ['state'], unique=False)
    op.create_index(op.f('ix_execution_tasks_task_type'), 'execution_tasks', ['task_type'], unique=False)
    op.create_table('recurring_schedulers',
    sa.Column('type', sa.Enum('SEND_REPORT', 'REMINDER', 'PIN_TASK', name='recurring_scheduler_type_enum'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'FIRED', 'PAUSED', 'CANCELED', 'ERROR', name='scheduler_state_enum'), nullable=False),
    sa.Column('origin_source', sa.Enum('COMMAND', 'WORKER', name='scheduler_origin_source_enum'), nullable=False),
    sa.Column('origin_id', sa.String(length=64), nullable=True),
    sa.Column('event_client_id', sa.String(length=64), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('interval_value', sa.Enum('SECONDS', 'MINUTES', 'DAYS', 'MONTHS', name='recurring_scheduler_interval_value_enum'), nullable=False),
    sa.Column('last_interval', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_recurring_schedulers_event_client_id'), 'recurring_schedulers', ['event_client_id'], unique=False)
    op.create_index(op.f('ix_recurring_schedulers_state'), 'recurring_schedulers', ['state'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.Enum('ADMIN', 'MEMBER', 'FIELD', name='role_name_enum'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('languages', sa.String(length=512), nullable=True),
    sa.Column('language_preference', sa.String(length=16), nullable=True),
    sa.Column('profile_picture', sa.String(length=512), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_app_view_record_id', sa.String(length=64), nullable=True),
    sa.Column('last_history_record_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['last_app_view_record_id'], ['user_app_view_records.client_id'], name='fk_users_last_app_view_record_id', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['last_history_record_id'], ['user_history_records.client_id'], name='fk_users_last_history_record_id', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cases',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'RESOLVING', 'RESOLVED', name='case_state_enum'), nullable=False),
    sa.Column('case_type_id', sa.String(length=64), nullable=True),
    sa.Column('type_label', sa.String(length=128), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('conversations_count', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_value', sa.JSON(), nullable=True),
    sa.Column('to_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_cases_case_type_id'), 'cases', ['case_type_id'], unique=False)
    op.create_index(op.f('ix_cases_created_by_id'), 'cases', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cases_state'), 'cases', ['state'], unique=False)
    op.create_index(op.f('ix_cases_updated_at'), 'cases', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cases_updated_by_id'), 'cases', ['updated_by_id'], unique=False)
    op.create_table('content_mention_links',
    sa.Column('content_mention_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('CASE_CONVERSATION_MESSAGE', 'TASK_DETAILS_MENTION', 'TASK_NOTE_MENTION', name='content_mention_link_entity_type_enum'), nullable=False),
    sa.Column('entity_client_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['content_mention_id'], ['content_mentions.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_content_mention_links_content_mention_id'), 'content_mention_links', ['content_mention_id'], unique=False)
    op.create_index(op.f('ix_content_mention_links_created_by_id'), 'content_mention_links', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_content_mention_links_entity_client_id'), 'content_mention_links', ['entity_client_id'], unique=False)
    op.create_index(op.f('ix_content_mention_links_entity_type'), 'content_mention_links', ['entity_type'], unique=False)
    op.create_table('execution_payloads',
    sa.Column('origin_source', sa.Enum('DELAYED_SCHEDULER', 'RECURRING_SCHEDULER', 'INSTANT', name='event_task_origin_source_enum'), nullable=False),
    sa.Column('origin_id', sa.String(length=64), nullable=True),
    sa.Column('event_client_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('execution_task_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['execution_task_id'], ['execution_tasks.client_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('execution_task_id')
    )
    op.create_index(op.f('ix_execution_payloads_event_client_id'), 'execution_payloads', ['event_client_id'], unique=False)
    op.create_table('images',
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('storage_provider', sa.Enum('S3', 'SHOPIFY', 'EXTERNAL', name='image_storage_provider_enum'), nullable=False),
    sa.Column('source_type', sa.Enum('UPLOADED', 'SHOPIFY_SYNC', 'GENERATED', name='image_source_type_enum'), nullable=False),
    sa.Column('source_reference', sa.Enum('S3_IMAGE_URL', 'SHOPIFY_IMAGE_URL', name='image_source_reference_enum'), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['last_event_id'], ['image_events.client_id'], name='fk_image_last_event_id', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_images_created_by_id'), 'images', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_images_deleted_at'), 'images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_images_storage_provider'), 'images', ['storage_provider'], unique=False)
    op.create_table('notification_pins',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_client_id', sa.String(length=128), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_client_id', name='uq_notification_pin_user_entity')
    )
    op.create_index(op.f('ix_notification_pins_entity_type'), 'notification_pins', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notification_pins_user_id'), 'notification_pins', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_client_id', sa.String(length=128), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uq_push_subscription_user_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('user_app_view_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_client_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_user_app_view_records_entity_client_id'), 'user_app_view_records', ['entity_client_id'], unique=False)
    op.create_index(op.f('ix_user_app_view_records_entity_type'), 'user_app_view_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_app_view_records_user_id'), 'user_app_view_records', ['user_id'], unique=False)
    op.create_table('user_history_records',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_value', sa.JSON(), nullable=True),
    sa.Column('to_value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_user_history_records_updated_at'), 'user_history_records', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_history_records_updated_by_id'), 'user_history_records', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_user_history_records_user_id'), 'user_history_records', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('audit_logs',
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_client_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.client_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('case_conversations',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'RESOLVING', 'RESOLVED', name='case_state_enum'), nullable=False),
    sa.Column('last_message_seq', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_case_conversations_case_id'), 'case_conversations', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_conversations_created_by_id'), 'case_conversations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_case_conversations_state'), 'case_conversations', ['state'], unique=False)
    op.create_table('case_links',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('TASK', 'CUSTOMER', name='case_link_entity_type_enum'), nullable=False),
    sa.Column('entity_client_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ORIGIN', 'SUBJECT', 'CONTEXT', 'ACTOR', 'RESOLUTION', name='case_link_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('case_id', 'entity_type', 'entity_client_id', name='uq_case_link_case_entity')
    )
    op.create_index(op.f('ix_case_links_case_id'), 'case_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_links_entity_client_id'), 'case_links', ['entity_client_id'], unique=False)
    op.create_index(op.f('ix_case_links_entity_type'), 'case_links', ['entity_type'], unique=False)
    op.create_table('case_participants',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('last_read_message_seq', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_case_participant')
    )
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_user_id'), 'case_participants', ['user_id'], unique=False)
    op.create_table('image_annotations',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('annotation_type', sa.Enum('DRAW', 'ARROW', 'CIRCLE', 'RECTANGLE', 'TEXT', 'MEASUREMENT', 'HIGHLIGHT', name='image_annotation_type_enum'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_image_annotations_created_by_id'), 'image_annotations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_image_annotations_image_id'), 'image_annotations', ['image_id'], unique=False)
    op.create_table('image_events',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='event_record_state_enum'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('UPLOAD_ITEM_IMAGE', 'UPLOAD_CASE_IMAGE', 'UPLOAD_MESSAGE_IMAGE', name='image_events_type_enum'), nullable=False),
    sa.Column('last_error', sa.Enum('UPLOAD_FAILED', 'INVALID_CONTENT_TYPE', 'STORAGE_UNAVAILABLE', 'FILE_TOO_LARGE', 'VIRUS_DETECTED', name='image_events_error_enum'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_image_events_created_by_id'), 'image_events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_image_events_image_id'), 'image_events', ['image_id'], unique=False)
    op.create_index(op.f('ix_image_events_state'), 'image_events', ['state'], unique=False)
    op.create_table('image_links',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('ITEM', 'CASE', 'CASE_CONVERSATION_MESSAGE', name='image_link_entity_type_enum'), nullable=False),
    sa.Column('entity_client_id', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('image_id', 'entity_type', 'entity_client_id', name='uq_image_link_image_entity')
    )
    op.create_index(op.f('ix_image_links_entity_client_id'), 'image_links', ['entity_client_id'], unique=False)
    op.create_index(op.f('ix_image_links_entity_type'), 'image_links', ['entity_type'], unique=False)
    op.create_index(op.f('ix_image_links_image_id'), 'image_links', ['image_id'], unique=False)
    op.create_table('pending_uploads',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'EXPIRED', name='pending_upload_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('upload_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_pending_uploads_created_by_id'), 'pending_uploads', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pending_uploads_status'), 'pending_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_pending_uploads_workspace_id'), 'pending_uploads', ['workspace_id'], unique=False)
    op.create_table('workspace_roles',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_workspace_roles_workspace_name')
    )
    op.create_index(op.f('ix_workspace_roles_role_id'), 'workspace_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_workspace_roles_workspace_id'), 'workspace_roles', ['workspace_id'], unique=False)
    op.create_table('case_conversation_messages',
    sa.Column('case_conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('has_been_edited', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_been_deleted', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_conversation_id'], ['case_conversations.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('case_conversation_id', 'message_seq', name='uq_message_seq')
    )
    op.create_index(op.f('ix_case_conversation_messages_case_conversation_id'), 'case_conversation_messages', ['case_conversation_id'], unique=False)
    op.create_index(op.f('ix_case_conversation_messages_created_by_id'), 'case_conversation_messages', ['created_by_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_role_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], deferrable=True),
    sa.ForeignKeyConstraint(['workspace_role_id'], ['workspace_roles.client_id'], deferrable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_workspace_memberships_user_workspace')
    )
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_case_conversation_messages_created_by_id'), table_name='case_conversation_messages')
    op.drop_index(op.f('ix_case_conversation_messages_case_conversation_id'), table_name='case_conversation_messages')
    op.drop_table('case_conversation_messages')
    op.drop_index(op.f('ix_workspace_roles_workspace_id'), table_name='workspace_roles')
    op.drop_index(op.f('ix_workspace_roles_role_id'), table_name='workspace_roles')
    op.drop_table('workspace_roles')
    op.drop_index(op.f('ix_pending_uploads_workspace_id'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_status'), table_name='pending_uploads')
    op.drop_index(op.f('ix_pending_uploads_created_by_id'), table_name='pending_uploads')
    op.drop_table('pending_uploads')
    op.drop_index(op.f('ix_image_links_image_id'), table_name='image_links')
    op.drop_index(op.f('ix_image_links_entity_type'), table_name='image_links')
    op.drop_index(op.f('ix_image_links_entity_client_id'), table_name='image_links')
    op.drop_table('image_links')
    op.drop_index(op.f('ix_image_events_state'), table_name='image_events')
    op.drop_index(op.f('ix_image_events_image_id'), table_name='image_events')
    op.drop_index(op.f('ix_image_events_created_by_id'), table_name='image_events')
    op.drop_table('image_events')
    op.drop_index(op.f('ix_image_annotations_image_id'), table_name='image_annotations')
    op.drop_index(op.f('ix_image_annotations_created_by_id'), table_name='image_annotations')
    op.drop_table('image_annotations')
    op.drop_index(op.f('ix_case_participants_user_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_table('case_participants')
    op.drop_index(op.f('ix_case_links_entity_type'), table_name='case_links')
    op.drop_index(op.f('ix_case_links_entity_client_id'), table_name='case_links')
    op.drop_index(op.f('ix_case_links_case_id'), table_name='case_links')
    op.drop_table('case_links')
    op.drop_index(op.f('ix_case_conversations_state'), table_name='case_conversations')
    op.drop_index(op.f('ix_case_conversations_created_by_id'), table_name='case_conversations')
    op.drop_index(op.f('ix_case_conversations_case_id'), table_name='case_conversations')
    op.drop_table('case_conversations')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_history_records_user_id'), table_name='user_history_records')
    op.drop_index(op.f('ix_user_history_records_updated_by_id'), table_name='user_history_records')
    op.drop_index(op.f('ix_user_history_records_updated_at'), table_name='user_history_records')
    op.drop_table('user_history_records')
    op.drop_index(op.f('ix_user_app_view_records_user_id'), table_name='user_app_view_records')
    op.drop_index(op.f('ix_user_app_view_records_entity_type'), table_name='user_app_view_records')
    op.drop_index(op.f('ix_user_app_view_records_entity_client_id'), table_name='user_app_view_records')
    op.drop_table('user_app_view_records')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_pins_user_id'), table_name='notification_pins')
    op.drop_index(op.f('ix_notification_pins_entity_type'), table_name='notification_pins')
    op.drop_table('notification_pins')
    op.drop_index(op.f('ix_images_storage_provider'), table_name='images')
    op.drop_index(op.f('ix_images_deleted_at'), table_name='images')
    op.drop_index(op.f('ix_images_created_by_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_execution_payloads_event_client_id'), table_name='execution_payloads')
    op.drop_table('execution_payloads')
    op.drop_index(op.f('ix_content_mention_links_entity_type'), table_name='content_mention_links')
    op.drop_index(op.f('ix_content_mention_links_entity_client_id'), table_name='content_mention_links')
    op.drop_index(op.f('ix_content_mention_links_created_by_id'), table_name='content_mention_links')
    op.drop_index(op.f('ix_content_mention_links_content_mention_id'), table_name='content_mention_links')
    op.drop_table('content_mention_links')
    op.drop_index(op.f('ix_cases_updated_by_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_updated_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_state'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_type_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_recurring_schedulers_state'), table_name='recurring_schedulers')
    op.drop_index(op.f('ix_recurring_schedulers_event_client_id'), table_name='recurring_schedulers')
    op.drop_table('recurring_schedulers')
    op.drop_index(op.f('ix_execution_tasks_task_type'), table_name='execution_tasks')
    op.drop_index(op.f('ix_execution_tasks_state'), table_name='execution_tasks')
    op.drop_index(op.f('ix_execution_tasks_next_retry_at'), table_name='execution_tasks')
    op.drop_table('execution_tasks')
    op.drop_index(op.f('ix_delayed_schedulers_state'), table_name='delayed_schedulers')
    op.drop_index(op.f('ix_delayed_schedulers_scheduled_for'), table_name='delayed_schedulers')
    op.drop_index(op.f('ix_delayed_schedulers_event_client_id'), table_name='delayed_schedulers')
    op.drop_table('delayed_schedulers')
    op.drop_index(op.f('ix_content_mentions_mention_table'), table_name='content_mentions')
    op.drop_index(op.f('ix_content_mentions_mention_id'), table_name='content_mentions')
    op.drop_table('content_mentions')
    op.drop_index(op.f('ix_case_types_entity_type'), table_name='case_types')
    op.drop_table('case_types')
    # ### end Alembic commands ###
