"""Plan 1: upholstery inventory projection migrations

Revision ID: a61def0ca46f
Revises: 3b39a3884912
Create Date: 2026-05-16 22:31:26.805016

Changes:
- Drop upholstery_inventory_threshold_policies table and its enums
- Add low_stock_threshold_meters column to upholstery_inventory
- Make amount_meters nullable on item_upholstery_requirement (supports MISSING_QUANTITY state)
- Add MISSING_QUANTITY enum value to item_upholstery_requirement_state_enum
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a61def0ca46f'
down_revision: Union[str, None] = '3b39a3884912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upholstery_inventory_threshold_policies_created_by_id', table_name='upholstery_inventory_threshold_policies')
    op.drop_index('ix_upholstery_inventory_threshold_policies_scope', table_name='upholstery_inventory_threshold_policies')
    op.drop_index('ix_upholstery_inventory_threshold_policies_upholstery_id', table_name='upholstery_inventory_threshold_policies')
    op.drop_index('ix_upholstery_inventory_threshold_policies_workspace_id', table_name='upholstery_inventory_threshold_policies')
    op.drop_table('upholstery_inventory_threshold_policies')
    op.add_column('upholstery_inventory', sa.Column('low_stock_threshold_meters', sa.Numeric(precision=14, scale=3), nullable=True))
    # ### end Alembic commands ###
    
    # Plan 1 additional migrations
    # Add MISSING_QUANTITY enum value to item_upholstery_requirement_state_enum
    op.execute("ALTER TYPE item_upholstery_requirement_state_enum ADD VALUE 'missing_quantity' BEFORE 'available'")
    
    # Make amount_meters nullable on item_upholstery_requirement
    op.alter_column('item_upholstery_requirements', 'amount_meters',
                    existing_type=sa.Numeric(precision=12, scale=3),
                    nullable=True,
                    existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse Plan 1 additional migrations
    op.alter_column('item_upholstery_requirements', 'amount_meters',
                    existing_type=sa.Numeric(precision=12, scale=3),
                    nullable=False,
                    existing_nullable=True)
    
    # Cannot directly remove enum value in PostgreSQL, so we rename the enum and recreate without the value
    # For downgrade, we'll skip the enum removal as it's complex
    # The enum value removal would need to be done manually if needed
    
    op.drop_column('upholstery_inventory', 'low_stock_threshold_meters')
    op.create_table('upholstery_inventory_threshold_policies',
    sa.Column('workspace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('scope', postgresql.ENUM('workspace_default', 'upholstery', name='threshold_policy_scope_enum'), autoincrement=False, nullable=False),
    sa.Column('upholstery_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('low_stock_minimum_meters', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True),
    sa.Column('low_stock_ratio', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('out_of_stock_epsilon_meters', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=True),
    sa.Column('escalation_policy', postgresql.ENUM('none', 'recommend_reorder', 'escalate_to_procurement', name='sourcing_escalation_policy_enum'), autoincrement=False, nullable=True),
    sa.Column('warning_tier', postgresql.ENUM('normal', 'low_stock_warning', 'urgent_reorder', name='inventory_warning_tier_enum'), autoincrement=False, nullable=True),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.CheckConstraint("scope <> 'upholstery'::threshold_policy_scope_enum OR upholstery_id IS NOT NULL", name='ck_utp_upholstery_scope_requires_id'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name='ck_utp_effective_window'),
    sa.CheckConstraint('low_stock_minimum_meters IS NULL OR low_stock_minimum_meters >= 0::numeric', name='ck_utp_low_stock_min_positive'),
    sa.CheckConstraint('low_stock_ratio IS NULL OR low_stock_ratio >= 0::numeric AND low_stock_ratio <= 1::numeric', name='ck_utp_low_stock_ratio_range'),
    sa.CheckConstraint('out_of_stock_epsilon_meters IS NULL OR out_of_stock_epsilon_meters >= 0::numeric', name='ck_utp_epsilon_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], name='upholstery_inventory_threshold_policies_created_by_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], name='upholstery_inventory_threshold_policies_deleted_by_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], name='upholstery_inventory_threshold_policies_updated_by_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upholstery_id'], ['upholsteries.client_id'], name='upholstery_inventory_threshold_policies_upholstery_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], name='upholstery_inventory_threshold_policies_workspace_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id', name='upholstery_inventory_threshold_policies_pkey'),
    sa.UniqueConstraint('workspace_id', 'scope', 'upholstery_id', 'effective_from', name='uq_upholstery_inv_threshold_policies_unique')
    )
    op.create_index('ix_upholstery_inventory_threshold_policies_workspace_id', 'upholstery_inventory_threshold_policies', ['workspace_id'], unique=False)
    op.create_index('ix_upholstery_inventory_threshold_policies_upholstery_id', 'upholstery_inventory_threshold_policies', ['upholstery_id'], unique=False)
    op.create_index('ix_upholstery_inventory_threshold_policies_scope', 'upholstery_inventory_threshold_policies', ['scope'], unique=False)
    op.create_index('ix_upholstery_inventory_threshold_policies_created_by_id', 'upholstery_inventory_threshold_policies', ['created_by_id'], unique=False)
    # ### end Alembic commands ###
