"""add_transition_reason_columns

Additive only (system_transition_reasons phase 1, criterion 9): `upgrade` adds two
nullable indexed columns, `downgrade` drops them. No data is touched in either
direction and nothing writes these columns yet.

Hand-written rather than autogenerated on purpose. Autogenerate sweeps in pre-existing
schema drift unrelated to this phase (the same drift `67cfba8fcb2d` documents:
email_sync_states unique constraint, two step_state_records indexes present in the DB
but not in the models). That drift is owned by the declared-worker-states baseline as
separate repo-health work — acting on it here would be destructive and out of scope.

Revision ID: a7d21f4c8b03
Revises: 67cfba8fcb2d
Create Date: 2026-07-31 00:00:00.000000
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'a7d21f4c8b03'
down_revision: Union[str, None] = '67cfba8fcb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('step_state_records', sa.Column('transition_reason', sa.String(length=32), nullable=True))
    op.create_index('ix_step_state_records_transition_reason', 'step_state_records', ['transition_reason'])
    op.add_column('user_shift_state_records', sa.Column('transition_reason', sa.String(length=32), nullable=True))
    op.create_index(
        'ix_user_shift_state_records_transition_reason',
        'user_shift_state_records',
        ['transition_reason'],
    )


def downgrade() -> None:
    op.drop_index('ix_user_shift_state_records_transition_reason', table_name='user_shift_state_records')
    op.drop_column('user_shift_state_records', 'transition_reason')
    op.drop_index('ix_step_state_records_transition_reason', table_name='step_state_records')
    op.drop_column('step_state_records', 'transition_reason')
