"""create_pause_reasons_table

Revision ID: ad5da5b32355
Revises: 8d6c3e7f0b21
Create Date: 2026-07-22 13:17:08.993078
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = 'ad5da5b32355'
down_revision: Union[str, None] = '8d6c3e7f0b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PAUSE_REASON_TYPE = postgresql.ENUM(
    "PERSONAL",
    "BLOCKER",
    name="pause_reason_type_enum",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _PAUSE_REASON_TYPE.create(op.get_bind(), checkfirst=True)
    op.create_table('pause_reasons',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('pause_type', _PAUSE_REASON_TYPE, nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('requires_description', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('is_system_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_pause_reasons_workspace_name')
    )
    op.create_index(op.f('ix_pause_reasons_created_by_id'), 'pause_reasons', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pause_reasons_updated_by_id'), 'pause_reasons', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_pause_reasons_deleted_by_id'), 'pause_reasons', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_pause_reasons_pause_type'), 'pause_reasons', ['pause_type'], unique=False)
    op.create_index(op.f('ix_pause_reasons_workspace_id'), 'pause_reasons', ['workspace_id'], unique=False)
    op.create_index('ix_pause_reasons_workspace_type', 'pause_reasons', ['workspace_id', 'pause_type'], unique=False)
    op.create_index('uq_pause_reasons_slug', 'pause_reasons', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pause_reasons_slug', table_name='pause_reasons')
    op.drop_index('ix_pause_reasons_workspace_type', table_name='pause_reasons')
    op.drop_index(op.f('ix_pause_reasons_workspace_id'), table_name='pause_reasons')
    op.drop_index(op.f('ix_pause_reasons_pause_type'), table_name='pause_reasons')
    op.drop_index(op.f('ix_pause_reasons_deleted_by_id'), table_name='pause_reasons')
    op.drop_index(op.f('ix_pause_reasons_updated_by_id'), table_name='pause_reasons')
    op.drop_index(op.f('ix_pause_reasons_created_by_id'), table_name='pause_reasons')
    op.drop_table('pause_reasons')
    _PAUSE_REASON_TYPE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
