"""add_analytics_aggregate_tables

Revision ID: befad87b3463
Revises: b9d3e4f12a87
Create Date: 2026-05-15 18:42:40.428837
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'befad87b3463'
down_revision: Union[str, None] = 'b9d3e4f12a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_work_stats',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_display_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('total_working_seconds', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_seconds', sa.Integer(), nullable=False),
    sa.Column('total_working_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_resolved_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', 'work_date', name='uq_user_daily_work_stats_workspace_user_date')
    )
    op.create_index('ix_user_daily_work_stats_user_date', 'user_daily_work_stats', ['user_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_user_daily_work_stats_user_id'), 'user_daily_work_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_daily_work_stats_workspace_id'), 'user_daily_work_stats', ['workspace_id'], unique=False)
    op.create_table('user_lifetime_stats',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_display_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('total_working_seconds', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_seconds', sa.Integer(), nullable=False),
    sa.Column('total_working_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_resolved_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_user_lifetime_stats_workspace_user')
    )
    op.create_index(op.f('ix_user_lifetime_stats_user_id'), 'user_lifetime_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_lifetime_stats_workspace_id'), 'user_lifetime_stats', ['workspace_id'], unique=False)
    op.create_index('ix_user_lifetime_stats_workspace_user', 'user_lifetime_stats', ['workspace_id', 'user_id'], unique=False)
    op.create_table('user_section_daily_work_stats',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('section_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('user_display_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('total_working_seconds', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_seconds', sa.Integer(), nullable=False),
    sa.Column('total_working_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_resolved_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', 'working_section_id', 'work_date', name='uq_user_section_daily_work_stats_workspace_user_section_date')
    )
    op.create_index('ix_user_section_daily_work_stats_section_date', 'user_section_daily_work_stats', ['working_section_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_user_section_daily_work_stats_user_id'), 'user_section_daily_work_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_section_daily_work_stats_working_section_id'), 'user_section_daily_work_stats', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_user_section_daily_work_stats_workspace_id'), 'user_section_daily_work_stats', ['workspace_id'], unique=False)
    op.create_table('working_section_daily_work_stats',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('working_section_id', sa.String(length=64), nullable=False),
    sa.Column('section_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('total_working_seconds', sa.Integer(), nullable=False),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_seconds', sa.Integer(), nullable=False),
    sa.Column('total_working_count', sa.Integer(), nullable=False),
    sa.Column('total_pause_count', sa.Integer(), nullable=False),
    sa.Column('total_ended_shift_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_count', sa.Integer(), nullable=False),
    sa.Column('total_issues_resolved_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['working_section_id'], ['working_sections.client_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('workspace_id', 'working_section_id', 'work_date', name='uq_working_section_daily_work_stats_workspace_section_date')
    )
    op.create_index('ix_working_section_daily_work_stats_section_date', 'working_section_daily_work_stats', ['working_section_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_working_section_daily_work_stats_working_section_id'), 'working_section_daily_work_stats', ['working_section_id'], unique=False)
    op.create_index(op.f('ix_working_section_daily_work_stats_workspace_id'), 'working_section_daily_work_stats', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_section_daily_work_stats_workspace_id'), table_name='working_section_daily_work_stats')
    op.drop_index(op.f('ix_working_section_daily_work_stats_working_section_id'), table_name='working_section_daily_work_stats')
    op.drop_index('ix_working_section_daily_work_stats_section_date', table_name='working_section_daily_work_stats')
    op.drop_table('working_section_daily_work_stats')
    op.drop_index(op.f('ix_user_section_daily_work_stats_workspace_id'), table_name='user_section_daily_work_stats')
    op.drop_index(op.f('ix_user_section_daily_work_stats_working_section_id'), table_name='user_section_daily_work_stats')
    op.drop_index(op.f('ix_user_section_daily_work_stats_user_id'), table_name='user_section_daily_work_stats')
    op.drop_index('ix_user_section_daily_work_stats_section_date', table_name='user_section_daily_work_stats')
    op.drop_table('user_section_daily_work_stats')
    op.drop_index('ix_user_lifetime_stats_workspace_user', table_name='user_lifetime_stats')
    op.drop_index(op.f('ix_user_lifetime_stats_workspace_id'), table_name='user_lifetime_stats')
    op.drop_index(op.f('ix_user_lifetime_stats_user_id'), table_name='user_lifetime_stats')
    op.drop_table('user_lifetime_stats')
    op.drop_index(op.f('ix_user_daily_work_stats_workspace_id'), table_name='user_daily_work_stats')
    op.drop_index(op.f('ix_user_daily_work_stats_user_id'), table_name='user_daily_work_stats')
    op.drop_index('ix_user_daily_work_stats_user_date', table_name='user_daily_work_stats')
    op.drop_table('user_daily_work_stats')
    # ### end Alembic commands ###
