"""add_completed_count_to_analytics

Revision ID: c9d382a037e5
Revises: c5d6e7f8a9b0
Create Date: 2026-07-15 16:51:00.009400
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'c9d382a037e5'
down_revision: Union[str, None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('total_completed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_daily_work_stats', sa.Column('total_completed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lifetime_stats', sa.Column('total_completed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_section_daily_work_stats', sa.Column('total_completed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('working_section_daily_work_stats', sa.Column('total_completed_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('working_section_daily_work_stats', 'total_completed_count')
    op.drop_column('user_section_daily_work_stats', 'total_completed_count')
    op.drop_column('user_lifetime_stats', 'total_completed_count')
    op.drop_column('user_daily_work_stats', 'total_completed_count')
    op.drop_column('task_steps', 'total_completed_count')
    # ### end Alembic commands ###
