"""add_recorded_time_marked_wrong_to_step_state_records

Revision ID: cf79311a956f
Revises: f1aff3910fd5
Create Date: 2026-05-18 18:33:16.154207
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'cf79311a956f'
down_revision: Union[str, None] = 'f1aff3910fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_state_records', sa.Column('recorded_time_marked_wrong', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_state_records', 'recorded_time_marked_wrong')
    # ### end Alembic commands ###
