"""Connecteam Time Clock — Time Activities pull client (historical shift import).

Wraps ``GET /time-clock/v1/time-clocks/{timeClockId}/time-activities`` (activityTypes=shift):
the *worked* records generated by clock-in/clock-out, grouped by user. Used only by the
historical shift-curation script — the live path is webhook-driven.

Timestamps are Unix **seconds** and therefore absolute UTC; each shift's IANA ``timezone``
is only where the punch happened and is not needed to place the instant. A shift with a
missing/``null`` ``end`` is still open and is skipped by the caller. The API caps each
request at a 92-day range, so callers window larger imports.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import date, datetime, timezone

import httpx

logger = logging.getLogger(__name__)

_TIME_ACTIVITIES_PATH = "/time-clock/v1/time-clocks/{time_clock_id}/time-activities"
_MAX_RANGE_DAYS = 92
_RETRY_STATUS = {429, 500, 502, 503, 504}


@dataclass(frozen=True)
class ConnecteamShift:
    """One completed worked shift for a Connecteam user (absolute-UTC bounds)."""

    connecteam_user_id: str
    shift_id: str
    start_at: datetime
    end_at: datetime
    is_auto_clock_out: bool


@dataclass(frozen=True)
class ParsedTimeActivities:
    shifts: list[ConnecteamShift]
    skipped_open: int  # shifts with no `end` (still clocked in) — not importable


def _to_utc(timestamp: int | float) -> datetime:
    # Connecteam timestamps are Unix seconds → absolute UTC; the shift `timezone` is metadata.
    return datetime.fromtimestamp(float(timestamp), tz=timezone.utc)


def parse_time_activities(payload: dict) -> ParsedTimeActivities:
    """Pure parse of a Time Activities response into completed :class:`ConnecteamShift`s.

    Groups are ``data.timeActivitiesByUsers[]``; each has ``userId`` and ``shifts[]``. A
    shift needs a ``start.timestamp`` and a non-null ``end.timestamp`` to be importable;
    open shifts are counted and skipped. Deduplicated by ``shift.id`` (the stable
    time-activity identifier) within the response.
    """
    shifts: list[ConnecteamShift] = []
    skipped_open = 0
    seen: set[str] = set()

    groups = (payload.get("data") or {}).get("timeActivitiesByUsers") or []
    for group in groups:
        connecteam_user_id = str(group.get("userId")) if group.get("userId") is not None else None
        if not connecteam_user_id:
            continue
        for shift in group.get("shifts") or []:
            shift_id = shift.get("id")
            start = (shift.get("start") or {}).get("timestamp")
            end = (shift.get("end") or {}).get("timestamp")  # (shift.get("end") may be None)
            if shift_id is None or start is None:
                continue
            if end is None:
                skipped_open += 1
                continue
            if shift_id in seen:
                continue
            seen.add(shift_id)
            shifts.append(
                ConnecteamShift(
                    connecteam_user_id=connecteam_user_id,
                    shift_id=str(shift_id),
                    start_at=_to_utc(start),
                    end_at=_to_utc(end),
                    is_auto_clock_out=bool(shift.get("isAutoClockOut", False)),
                )
            )
    return ParsedTimeActivities(shifts=shifts, skipped_open=skipped_open)


class ConnecteamTimeActivitiesClient:
    """Thin async HTTP client for the Time Activities endpoint."""

    def __init__(self, *, api_key: str, base_url: str, timeout: float = 30.0, max_retries: int = 4):
        self._headers = {"X-API-KEY": api_key, "Accept": "application/json"}
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._max_retries = max_retries

    async def fetch_shift_activities(
        self,
        *,
        time_clock_id: str,
        start_date: date,
        end_date: date,
        user_ids: list[str] | None = None,
    ) -> ParsedTimeActivities:
        """Fetch completed shifts for ``[start_date, end_date]`` (≤92 days, inclusive)."""
        if (end_date - start_date).days > _MAX_RANGE_DAYS:
            raise ValueError(f"Connecteam range cannot exceed {_MAX_RANGE_DAYS} days.")
        url = self._base_url + _TIME_ACTIVITIES_PATH.format(time_clock_id=time_clock_id)
        # userIds is an array param; ReadMe-style APIs repeat the key. httpx encodes a list
        # value as repeated keys. Confirm the exact encoding with one real request.
        params: list[tuple[str, str]] = [
            ("startDate", start_date.isoformat()),
            ("endDate", end_date.isoformat()),
            ("activityTypes", "shift"),
        ]
        params += [("userIds", uid) for uid in (user_ids or [])]

        payload = await self._get_with_retry(url, params)
        return parse_time_activities(payload)

    async def list_time_clocks(self) -> dict:
        """Raw ``GET /time-clock/v1/time-clocks`` — used to discover the ``timeClockId``."""
        return await self._get_with_retry(self._base_url + "/time-clock/v1/time-clocks", [])

    async def _get_with_retry(self, url: str, params: list[tuple[str, str]]) -> dict:
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            for attempt in range(self._max_retries):
                response = await client.get(url, params=params, headers=self._headers)
                if response.status_code in _RETRY_STATUS and attempt < self._max_retries - 1:
                    backoff = min(2**attempt, 30)
                    logger.warning(
                        "connecteam.time_activities_retry | status=%s attempt=%s backoff=%ss",
                        response.status_code, attempt + 1, backoff,
                    )
                    await asyncio.sleep(backoff)
                    continue
                response.raise_for_status()
                return response.json()
        raise RuntimeError("unreachable")
