"""Byte-identity guard for the pre-refactor typical-times statement.

The snapshot is intentionally captured once before the item-aware refactor and
must not be regenerated by later phases.
"""

from datetime import datetime, timezone
from pathlib import Path

import pytest
from sqlalchemy.dialects import postgresql

from beyo_manager.services.queries.working_sections.get_working_section_typical_times import (
    typical_times_statement,
)


SNAPSHOT_PATH = Path(__file__).with_name("snapshots") / "typical_times_no_spec_sql.txt"


def compile_typical_times_sql(*, now: datetime | None = None) -> str:
    return str(typical_times_statement("ws_snapshot", now=now).compile(dialect=postgresql.dialect()))


@pytest.mark.parametrize(
    "kwargs",
    [{}, {"now": datetime(2026, 8, 22, tzinfo=timezone.utc)}, {"specs": ()}],
    ids=["default-clock", "injected-clock", "explicit-no-spec"],
)
def test_typical_times_statement_matches_pre_refactor_snapshot_at_both_clock_forms(kwargs):
    snapshot = SNAPSHOT_PATH.read_text()

    assert str(typical_times_statement("ws_snapshot", **kwargs).compile(dialect=postgresql.dialect())) == snapshot
